### ISSUE TITLE
CopyRight for prosjekter publisert på makecode.microbit.org

### ISSUE THREAD

**Issue by kolbjornengeland** [kodeklubben/oppgaver#1156]
Jeg vil gjerne legge inn noen oppgaver oversatt fra microsoft sine makecode-sider. Er dette mulig uten å bryte copyright på de orginale oppgavene?

Denne oppgaven er morsom: 
 https://makecode.microbit.org/projects/voting-machine

**Comment by tjesi** [comment]
Det går fint. Måten vi pleier å gjøre det på er å vise til hvor oppgaven kommer fra og si hvem som har oversatt. Se oppgaven [Felix og Herbert](https://oppgaver.kidsakoder.no/scratch/felix_og_herbert/felix_og_herbert) som eksempel. [Se markdown koden her](https://raw.githubusercontent.com/kodeklubben/oppgaver/master/src/scratch/felix_og_herbert/felix_og_herbert.md).

**Comment by tjesi** [comment]
Eg er forøvrig helt enig i at dette er en kul oppgave, og vil gjerne ha den inn på oppgavesidene. I dette tilfellet så er jo dashboardet ganske komplisert - kanskje klarer vi å forenkle det og bygge et nytt dashboard som en del av oppgaven? Burde være mulig. Samtidig er det morro å se hvordan man kan jukse / unngå at noen jukser. Se feks utfordringene og forklaringen i slutten av [Hermegåsa](https://oppgaver.kidsakoder.no/microbit/pxt_hermegaasa/hermegaasa).

**Comment by kolbjornengeland** [comment]
Det går helt fint å lage dashboard ved hjelp av blokker. Mulige forenklinger er å bruke input for å nullstille alle stemmer eller for å slette alle velgere. Legger noe ut i kveld.
