### ISSUE TITLE
Problem med 'Scratch: Jafsefisk'

### ISSUE THREAD

**Issue by jeskdm** [kodeklubben/oppgaver#1188]
Oppgave: http://oppgaver.kidsakoder.no//scratch/jafsefisk/jafsefisk
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/jafsefisk

Hei, vil bare rapportere en mulig oppdatering av skriptet. I steg to refereres det til en blokk "snu venstre" men det virker som om denne blokken ikke finnes i scratch 3.0.

**Comment by steinoro** [comment]
Riktig. I Scratch 3 er det `snu @turnLeft` som er riktig. Sender PR på dette.
