### ISSUE TITLE
gitter som offisiell support-kanal?

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#12]
Likte gitter :smile: Fint at vi kan referere til issues, pr, repo osv. Den åpne lesetilgangen med historikk er også kjekk for nye brukere som sliter med det samme som andre.

**Comment by arve0** [comment]
https://gitter.im/kodeklubben/oppgaver

**Comment by gahjelle** [comment]
Enig i at gitter fungerer bra. Lite overhead, og forhåpentligvis enkelt å bruke for de som har problemer.
