### ISSUE TITLE
Problem med 'Scratch: Astrokatt'

### ISSUE THREAD

**Issue by sitan2** [kodeklubben/oppgaver#1203]
Oppgave: https://oppgaver.kidsakoder.no/scratch/astrokatt/astrokatt
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/astrokatt/astrokatt.md

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

The link do not work because it is spelled wrongly: Gå til scratch.mit.edu. (but it points to "scrath", and that will not work.

**Comment by tjesi** [comment]
Thank you for telling us! The error is now fixed, and the website will be updated very soon. Closing this.
