### ISSUE TITLE
Problem med 'Web: Introduksjon til web'

### ISSUE THREAD

**Issue by herdis** [kodeklubben/oppgaver#1213]
Oppgave: https://oppgaver.kidsakoder.no/web/introduksjon_til_web/introduksjon_til_web
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/web/introduksjon_til_web/introduksjon_til_web.md

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Fått epost fra brukar: "Tenkte bare å gi dere en heads up på en feil jeg har funnet i en av oppgavesettene. Under https://oppgaver.kidsakoder.no/web/introduksjon_til_web/introduksjon_til_web så refereres det med en javascript-link til X-Ray Goggles.

I link-koden åpner første linje med "varscript = document.createElement('script');"
Det skulle naturligvis vært "var script ="..."

Kan nokon fikse?! 

Herdis :)
Takk for et bra opplegg :)

**Comment by tjesi** [comment]
Vi har sett på oppgaven, og funnet ut at det faktisk står "var script =..." i dag. Dette er altså ikke en mulig endring for å få dette til å funke. Det er mulig å bare gi linken direkte, og så be folk legge den til i bokmerkene.

Derimot så ser vi at verktøyet som det linkes til skal legges ned i desember, som gjør at oppgaven i praksis blir ubrukelig fra det tidspunktet. I såfall bør oppgaven fjernes (i praksis: ikke slettes, men merkes som "false", som gjør at den ikke vises blant oppgavene eller spillelistene).

Derimot er vi interessert i å høre fra de som har benyttet seg av oppgaven om hvordan det har gått, og om de evt vet om et annet verktøy som vi kan bruke istedenfor fra desember av. Kan du sjekke med den personen som tok kontakt?

**Comment by tjesi** [comment]
Vi har fikset feilen. Vi la også merke til at dette verktøyet utgår i desember og vil ikke kunne brukes etter dette. Oppretter nytt issue på dette.
