### ISSUE TITLE
Problem med 'Scratch: Jafsefisk'

### ISSUE THREAD

**Issue by niclan** [kodeklubben/oppgaver#1217]
Oppgave: https://oppgaver.kidsakoder.no/scratch/jafsefisk/jafsefisk

Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/jafsefisk/jafsefisk.md

Hei. Vi kjørte jafsefisk på kodeklubben vår sist onsdag. Vi så følgende problemer:
1. Linje 55 "Hvordan ser den ut? Hvorfor gjør den dette?" Dette er et retorisk spørsmål. Bør ikke ha checkbox.
1. Linje 59 Barna har problemer med "flipping", foreslår å bare ha "flipping".
1. Ganske mange av barna hadde mistet byttedyret lenge før linje 181. Foreslår å legge inn "vis" kloss allerede rundt linje 142

**Comment by vegardbb** [comment]
@niclan, jeg har en branch som tar for seg denne saken på min *oppaver*-fork, men jeg sliter litt med å forstå punkt nummer 2, utover at formuleringen må endres. Vil du fjerne ordet "flipping"? Fjerne alt etter ordet i setningen?

**Comment by niclan** [comment]
Jeg mente vist at "manisk" burde bort.  "flippe" forstår barna, de flipper flasker ved enhver anledning.
