### ISSUE TITLE
Feil brikke i siste kodelisting

### ISSUE THREAD

**Issue by niclan** [kodeklubben/oppgaver#1221]
Oppgave: https://oppgaver.kidsakoder.no/scratch/gangemesteren/gangemesteren
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/gangemesteren/gangemesteren.md

Nederst i oppgaven  brukes rød brikke "slett".  Den skal være penne brikken "slett alt".

**Comment by vegardbb** [comment]
@gahjelle; @tjesi - kan en av dere tilordne meg denne oppgava, så retter jeg opp kodeblokken både i bokmål - og nynorsk - versjonen på forken min?

**Comment by tjesi** [comment]
Hei @vegardbb ! Supert at du kan fikse. Du trenger ikke bli tilordnet oppgaven, du kan bare sende inn en PR så kan vi godkjenne den.
