### ISSUE TITLE
Feil ved pdf

### ISSUE THREAD

**Issue by herdis** [kodeklubben/oppgaver#1226]
Sideoppsettet i pdf-dokumentene er ikke optimale for print.
Overskrift nederst på sida. Setninger som blir kutta. For mye luft.

**Comment by Skagevang** [comment]
Dette bør flyttes til codeclub-viewer repoet. Ingenting man får gjort med det på dette repoet

**Comment by herdis** [comment]
Er det noko du kan gjere?


tir. 17. des. 2019 kl. 17:41 skrev Ole-Martin Skagevang <
notifications@github.com>:

**Comment by herdis** [comment]
Hei, for å sikre at dette ikkje går i glømmeboka, for det er ganske viktig. Kva må til for å få dette fiksa event flytta til codeclub-viewer repoet?

**Comment by Skagevang** [comment]
Laget issue i codeclub-viewer nå. Så kan hvem som helst sende pull request på det :) https://github.com/kodeklubben/codeclub-viewer/issues/679
