### ISSUE TITLE
Problem med 'Microbit: Pxt blinkende hjerte' PDF-fil: engelske navn på klossene

### ISSUE THREAD

**Issue by josteitv** [kodeklubben/oppgaver#1229]
Oppgave: https://oppgaver.kidsakoder.no/microbit/pxt_blinkende_hjerte/pxt_blinkende_hjerte
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/microbit/pxt_blinkende_hjerte/pxt_blinkende_hjerte.md

PDF'filene har engelske navn på klossene.

Eksempel fra https://oppgaver.kidsakoder.no/microbit/pxt_blinkende_hjerte/pxt_blinkende_hjerte.pdf

![image](https://user-images.githubusercontent.com/952413/71848897-fe89dc80-30d0-11ea-9c9a-5878d22dc293.png)

**Comment by Skagevang** [comment]
Hei. Nå ser det ut som det er på norsk igjen. Det er kanskje en bug hos oss når PDFene blir laget, siden disse rendres hos makecode
