### ISSUE TITLE
Problem med 'Web: Introduksjon til web'

### ISSUE THREAD

**Issue by Vargeli** [kodeklubben/oppgaver#1235]
Oppgave: https://oppgaver.kidsakoder.no/web/introduksjon_til_web/README
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/web/introduksjon_til_web/README.md

Jeg vil gjerne bruke denne oppgaven (Introduksjon til HTML) i undervisning på 8. trinn, ungdomsskolen. Jeg får imidlertid ikke programmet X-Ray Goggles til å kjøre. Jeg får heller ikke feilmelding. 
Her er linken som ikke virker:
javascript:(function () {var script=document.createElement('script');script.src='https://goggles.mozilla.org'+'/webxray.js';script.className='webxray';script.setAttribute('data-lang','en-US');script.setAttribute('data-baseuri','https://goggles.mozilla.org');document.body.appendChild(script);}())

Mvh Elin Vargervik

**Comment by tjesi** [comment]
Hei,

Det ser ut som at dette verktøyet ble lagt ned i desember i fjor: https://foundation.mozilla.org/en/blog/putting-away-our-x-ray-goggles.

Eg har dessverre ikke kjennskap til tilsvarende verktøy som kan brukes istedenfor...

Tjerand

**Comment by tjesi** [comment]
Vi har nå lagt inn alternative måter å gjøre dette på.
