### ISSUE TITLE
Problem med 'Elm: 01 prov i nettleser'

### ISSUE THREAD

**Issue by irenk89** [kodeklubben/oppgaver#1236]
Oppgave: https://oppgaver.kidsakoder.no/elm/01_prov_i_nettleser/01_prov_i_nettleser
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/elm/01_prov_i_nettleser/01_prov_i_nettleser.md

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.
Jeg prøver meg på en ipad, på nettleseren Google crome. Men kodene <h1> og <p> fungerer ikke inne på ELM siden. Uansett hva jeg gjør så vil ikke programmet godta koden, så denne mener jeg er missledende.

**Comment by tjesi** [comment]
Eg prøvde "hello"-eksempelet på https://elm-lang.org/examples/hello, og det funker fint. Pass på at koden du skriver faktisk er Elm, det er eneste språket den forstår.
