### ISSUE TITLE
Problem med 'Arduino: 7 segment display'

### ISSUE THREAD

**Issue by ArniBoii** [kodeklubben/oppgaver#1237]
Oppgave: https://oppgaver.kidsakoder.no/arduino/7_segment_display/7_segment_display
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/arduino/7_segment_display/7_segment_display.md

Beskriv ditt problem her. Arduino: 1.8.12 (Windows 10), Board: "Arduino Uno"

C:\Users\AHegg\Documents\Arduino\sketch_may22c\sketch_may22c.ino: In function 'void loop()':

sketch_may22c:45:5: error: 'tegn_3' was not declared in this scope

     tegn_3();

     ^~~~~~

C:\Users\AHegg\Documents\Arduino\sketch_may22c\sketch_may22c.ino:45:5: note: suggested alternative: 'tegn_2'

     tegn_3();

     ^~~~~~

     tegn_2

exit status 1
'tegn_3' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.    Dette kom etter at jeg hadde skrevet, og så kopiert over koden. "void loop() {
    tegn_0();
    delay(500);
    tegn_1();
    delay(500);
    tegn_2();
    delay(500);
    tegn_3();
    delay(500);
}"                              Bruker google chrome, Arduino IDE 1.8.12

**Comment by tjesi** [comment]
Er du på steg 4 nå? Husk at du må ha funksjonene tegn_0 til tegn_3 ovenfor koden din, slik som vist i steg 3 oppgaven. De må ikke fjernes når du går videre.
