### ISSUE TITLE
Får ikke kjørt ./setup

### ISSUE THREAD

**Issue by oaramsda** [kodeklubben/oppgaver#13]
Så på videoen på youtube om hvordan å sette opp for å bidra med oppgaver.

Får feilmelding: ./setup: line 3: npm: command not found

**Comment by kwrl** [comment]
Har du installert node.j?

**Comment by kwrl** [comment]
Node.js

**Comment by oaramsda** [comment]
Nei. Hvordan gjør jeg det?

**Comment by oaramsda** [comment]
Ja

**Comment by kwrl** [comment]
Nei, de skal i utgangspunktet ikke det. Bruker du windows, os x eller linux?

**Comment by oaramsda** [comment]
windows

**Comment by kwrl** [comment]
Jeg vil tippe at problemet ditt er at npm ikke har blitt lagt til i PATH. Prøv å finne ut hvor npm installasjonen din ligger og legg den mappen til i path. Hvis du lurer på hvordan man gjør det så finner du det ved et kjapt søk etter "window add to path".

**Comment by oaramsda** [comment]
Har C:\Users\OleAndreas\AppData\Roaming\npm i PATH så er vel ikke det.

**Comment by arve0** [comment]
vil bli lukket av arve0/codeclub_lesson_builder#72

**Comment by arve0** [comment]
Reinstallasjon av Node løste denne.
