### ISSUE TITLE
Kilde appinventor "Kom i gang"

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#149]
Kom over [denne](http://appinventor.mit.edu/explore/sites/all/files/hourofcode/TalkToMePart1.pdf), som ligner meget på #145. @tjesi Har du basert oppgaven på den? I så tilfelle må vi ordne lisens og kilde.

**Comment by tjesi** [comment]
Ja, delvis. Eg var ikke klar over denne pdf-en, men å lage en app ved navn
"talk to me" er inspirert fra deres nettsider. Tenkte egentlig å lage en
som sier hello world istedet, men tiden strakk ikke til før eg skulle kjøre
kurset.

Eg tenkte å gå over oppgaven på nytt og gjøre endringer.

Tjerand

2015-11-11 17:55 GMT+01:00 Arve Seljebu <notifications@github.com>:

**Comment by arve0** [comment]
Ok. Vær obs på at endringer allerede er påbegynt: #147
