### ISSUE TITLE
Legg til code.org-oppleggene Star Wars og Minecraft

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/oppgaver#154]
Det er kommet to nye "opplegg" på code.org, nemlig Star Wars (der du lærer om events og kan lage ditt eget spill), og Minecraft, som ligner litt på Angry-birds opplegget, men virker bedre og morsommere.
Foreslår å legge lenker til disse to oppleggene inn sammen med Angry Birds og Frozen-linkene.

**Comment by arve0** [comment]
Takk! :octocat:
