### ISSUE TITLE
Problem med 'Microbit: Pxt snake'

### ISSUE THREAD

**Issue by bricklabz** [kodeklubben/oppgaver#1594]
Oppgave: https://oppgaver.kidsakoder.no/microbit/pxt_snake/snake
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/microbit/pxt_snake/snake.md

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Mac 13.3.1 (22E261), Chrome Version 113.0.5672.63:
- Steg 2 har feil i at koden skal inn i updateSnake-funksjonen og ikke inn i "ved start"-blokka. Bildene må oppdateres
- De mørke blokkene er ikke beskrevet ordentlig: Hvordan lages de? Hva må endres i koden for å lage dem? Når bytter man mellom blokker og Java?
- Bildene bytter språk mellom engelsk og norsk som gjør det vanskelig å følge med og sammenligne koden
-

**Comment by lluiscampos** [comment]
Hei @bricklabz og takk for din rapport,

Jeg har en PR til å adresse problemene du har beskrevet. Se #1595

>  * Steg 2 har feil i at koden skal inn i updateSnake-funksjonen og ikke inn i "ved start"-blokka. Bildene må oppdateres

Jeg har oppdatert alle snippene til å ha funksjon de må skrives inn.

> 
>     * De mørke blokkene er ikke beskrevet ordentlig: Hvordan lages de? Hva må endres i koden for å lage dem? Når bytter man mellom blokker og Java?

Jeg prøvde å fikse dette også. Grunn at de are mørke er ute av kontroll av oss men jeg har skrev en hint om hvor kan man finne disse klosser.

> 
>     * Bildene bytter språk mellom engelsk og norsk som gjør det vanskelig å følge med og sammenligne koden

Også fikset! Nå blir de alle på norsk.

**Comment by lluiscampos** [comment]
@lahetisv I think you can close now this issue.
