### ISSUE TITLE
Problem med 'Scratch: Hvor i all verden del1'

### ISSUE THREAD

**Issue by BDQZXx** [kodeklubben/oppgaver#1602]
Oppgave:
https://oppgaver.kidsakoder.no/scratch/hvor_i_all_verden_del1/hvor_i_all_verden_del1

Oppgavens kildekode:
https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/hvor_i_all_verden_del1/hvor_i_all_verden_del1.md

Scratch har ikke helikopter figur og europakart bakgrunn.

**Comment by BDQZXx** [comment]
Oppgaven må enten slettes eller omskrives til det som Scratch har på sin side.

**Comment by nimrof** [comment]
Hei @BDQZXx,
Laget en pr. som fikser helikopteret som ikke lengere finnes i scratch v3

europakartet ligger med oppgaven og ligger ikke i scratch
![image](https://github.com/kodeklubben/oppgaver/assets/9848846/17f4fea5-b232-41be-bf95-094460fcb2d7)
