### ISSUE TITLE
Videregående python + python?

### ISSUE THREAD

**Issue by okpedersen** [kodeklubben/oppgaver#165]
Det har, såvidt jeg vet, vært snakk om å samle alle Python-oppgavene. Mange oppgaver (dvs. de som ikke omhandler Pygame Zero) i de videregående oppgavesettene kunne like gjerne vært blant de vanlige Python-oppgavene - det blir et "falskt" skille. Spørsmålet da blir om alle oppgavene skal samles - og videregående kurs kan sette opp egne spillelister - eller om vi skal fortsette å holde de separert?
I tillegg, om vi ønsker å slå sammen, skal Pygame Zero-oppgavene ligge sammen med Python-oppgavene (men merkes på egen måte) eller skal vi holde disse for seg selv?

Om vi ønsker å slå sammen oppgavene gjør jeg gjerne dette, men ønsker å få det avklart før de ulike kodeklubbene starter opp igjen.

(cc @arve0 @tjesi @gahjelle )

**Comment by tjesi** [comment]
Vi burde ha alle oppgaver i Python samlet i ett kurs, og opprette passende
spillelister. Dette gjør også at vi trenger en gjennomgang av hvordan
oppgavene er kategorisert i vanskligshetsgrad. Ang Pygame Zero så vet eg
ikke helt, vil tro beste er å ha alt under Python og merke ekstra?

Samme med Java, burde bare hete Java, også merkes bedre, istedet for å
kalle alt JavaFX. Burde være mulig å legge inn oppgavesett fra gode, gamle
it1103 - java grunnkurs inn her.

Tjerand

23. januar 2016 kl. 14.03 skrev Ole Kristian Pedersen <
notifications@github.com>:

**Comment by okpedersen** [comment]
Jeg tror at det å begynne oppgavenavnet med f.eks. '[PGZ]' vil holde, ihvertfall midlertidig. Eks. '[PGZ] Hangman'. Ang. vansklighetsgrad, så tror jeg mange Python-oppgaver vil trenge en gjennomgang om vi skal følge retningslinjene beskrevet i ![README-Nivå og PR](https://github.com/kodeklubben/oppgaver#niv%C3%A5-og-pr)

**Comment by arve0** [comment]
:+1: La oss få det gjort!

> Ang. vansklighetsgrad, så tror jeg mange Python-oppgaver vil trenge en gjennomgang om vi skal følge retningslinjene beskrevet i README-Nivå og PR.

Det viktigste er å være konsistent, det er vi ikke nå. En start er nok å være konsistent på ett kurs, feks python, deretter ta en gjennomgang på de andre kursene.

**Comment by arve0** [comment]
> Om vi ønsker å slå sammen oppgavene gjør jeg gjerne dette, men ønsker å få det avklart før de ulike kodeklubbene starter opp igjen.

Når starter dere i Trondheim?

**Comment by okpedersen** [comment]
Da kommer det en PR snart. Forhåpentligvis i løpet av helga, da vi starter i Trondheim førstkommende mandag.

**Comment by arve0** [comment]
Ser gull ut dette.

**Comment by okpedersen** [comment]
Løses med #166 

Lukker denne.
