### ISSUE TITLE
Oppgaver på nynorsk

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/oppgaver#170]
(Fra Tjerand)
Det er etterspurt kodeoppgaver på nynorsk, og noen har startet å oversette. se vedlegg. skal vi lage en kursmappe med oppgaver på nynorsk, eller legge til i eksisterende og merke de eller noe?

[title.docx](https://github.com/kodeklubben/oppgaver/files/118716/title.docx)

**Comment by NorwegianKiwi** [comment]
(Fra Arve)
Med Lance Olavs siste arbeid, så er oversettelse relativt trivielt.

Siste bit er denne PR: https://github.com/arve0/codeclub_lesson_builder/pull/179, som har blitt hengende.

Og noen må selvfølgelig ta jobben med oversettelsen.

**Comment by NorwegianKiwi** [comment]
Jeg er enig i at selv applikasjonen rundt er nå lett å ha på bokmål og nynorsk (og vi kan ha knapp oppe i menyen der man kan bytte lett), men vi (eller ihvertfall jeg) har ikke tenkt ut hvordan selve oppgavene kan være på to (eller flere) språk ennå.

I dag ligger f.eks. skilpadder-oppgavene i filen kodeklubben/oppgaver/src/python/skilpadder/skilpadder.md

Vi kunne f.eks. hatt nynorsk i
1) kodeklubben/oppgaver/src/python/skilpadder_nn_NO/skilpadder.md

eller
2) kodeklubben/oppgaver/src/python/skilpadder/skilpadder_nn_NO.md

eller vi kunne delt opp begge:
3)
kodeklubben/oppgaver/src/python/skilpadder/nb_NO/skilpadder.md
kodeklubben/oppgaver/src/python/skilpadder/nn_NO/skilpadder.md


Jeg tror jeg foretrekker 1 eller 3, for da kan man kalle den innerste filen sitt "rette" navn på det språket (er det kanskje skilpaddar.md på nynorsk?)

Eller overkompliserer jeg nå?

**Comment by NorwegianKiwi** [comment]
Eller så kan man selvsagt ha en "kopi" av hele treet på hvert sitt språk:
4)
kodeklubben/oppgaver/src/nb_NO/python/skilpadder/skilpadder.md
kodeklubben/oppgaver/src/nn_NO/python/skilpaddar/skilpaddar.md

**Comment by arve0** [comment]
1, 3 og 4 vil kreve at bildene er dobbelt opp, eller at man endrer lenkene.

2 er relativ enkel å ordne med heuristikken "det er en fil med navnet *.nn_NO.md i mappen, nynorsk oppgave finnes". Filnavnet trenger ikke være det samme.

Trur jeg foretrekker 2.

**Comment by NorwegianKiwi** [comment]
Godt poeng, da tror jeg også at 2 er best.

Et annet punkt det må tas stilling til, er om man skal vise bokmål-sidene dersom nynorsk mangler, eller om disse skal være "adskilt" (altså om man skal ha fallback). Valg 2 vil gjøre det enklere å lage fallback,  ihvertfall hvis filnavnet er det samme. Jeg tror fallback er lurt, ellers "må" man oversette alt før man kan begynne å bruke det.

Valg 2 betyr også at vi ikke trenger å endre på det som ligger der i dag allerede.

Vil bare nevne en 5. måte, men har egentlig ikke så stor tro på den (men kom gjerne med overbevisende argumenter):
5) Skrive alle oversettelsene i samme fil.
Men jeg tror dette blir fort rotete, og jeg kan ikke se noen fordeler fremfor å ha to filer liggende "ved siden av hverandre"

**Comment by gahjelle** [comment]
Veldig bra arbeid som har vært gjort for mulighet til flere språk i applikasjonen. Jeg vet at Arve og jeg diskuterte noir lignende for en tid tilbake, da i konteksten år jeg hadde lyst å oversette noen av oppgavene våre til engelsk. Tror aldri noe ble gjort med dette, men mulig vi tenkte noen smarte tanker. Dog finner jeg ikke igjen den diskusjonen, er du flinkere en meg Arve?

Det sagt, jeg tror vi bør gjøre dette så enkelt som mulig, og alternativ 2 er nok min favoritt også. Den vil skalere dårlig. For eksempel om vi en dag har 20 språk slik codeclub-uk har vil nok alternativ 4 være mye mer ryddig. Men jeg ser ikke at vi er på vei dit, og om det skulle skje kan vi omorganisere i fremtiden.

Litt mer viktig å tenke gjennom er at det per i dag ikke er en 1-til-1-sammenheng mellom kataloger og oppgaver. Vi har nesten det, men byggeverktøyet har så langt ikke krevd det. Og vi har for eksempel noen scratchoppgaver, for eksempel Hvor i all verden?, som er delt i flere deler, men er organisert i en katalog. Da må vi være litt mer forsiktig med heuristikken :)

Et par forslag til presisering av alternativ 2:
2a) Vi kan kreve 1-til-1 mellom oppgaver og kataloger. Det er ikke veldig mye som må omorganiseres.
2b) En solid løsning vil være å bruke yaml-headeren til å koble oppgavene. Jeg tror vi har language på de fleste oppgavene allerede, og for eksempel en `original: skilpadder.md` ble holde for å koble oppgaver på en enkel måte.

Det er sikkert andre løsninger også. Men av disse foretrekker nok jeg 2b. Det blir kanskje noe overhead i prosesseringen (?), men er mer fleksibelt i forhold til videre utvikling. Vi har jo for eksempel snakket om å skrive noen veiledninger som også kan bli md-filer liggende i de forskjellige katalogene.

**Comment by tjesi** [comment]
skal vi gå for alternativ 2? har tre oppgavesett på nynorsk som er klare til å legges ut så snart vi har en løsning for dette

**Comment by arve0** [comment]
Ja, jeg stemmer for 2b med [nested mapping](http://yaml.org/YAML_for_ruby.html#nested_mappings):

```yaml
---
title: Straffespark
languages:
  nn-NO: straffespark.nn.md
  en-GB: penalty.md
---
```

Så må det bestemmes hva som gjøres når nynorsk velges. Skal kun oppgaver på nynorsk vises i index?

**Comment by arve0** [comment]
Og så må noen oversette UI: https://github.com/arve0/codeclub_lesson_builder/tree/master/assets/locales

**Comment by tjesi** [comment]
ja, kun vise nynorsk. om en vil ha bokmål så må en gå til den siden istedet. det vil være få oppgaver i starten, men det er stor interesse for å oversette fremover.

fikser oversettelse.

**Comment by tjesi** [comment]
[translation.txt](https://github.com/kodeklubben/oppgaver/files/153539/translation.txt)

**Comment by arve0** [comment]
Litt statistikk. Siden 1. januar er det 527 økter av 48 542, 1.09%, som har nettleseren sin satt til nynorsk.

**Comment by steinoro** [comment]
Alt av Scratch, Python og Web er omsett til nynorsk. Dei fleste Processing-oppgåvene og nokre Micro:bit-oppgåver òg.

**Comment by tjesi** [comment]
Vi har nå fått nynorsk (og andre språk) som GUI på de nye sidene, i tillegg til å ha oversatt indeks-filene, oppgaver, lærerveiledninger og scratchblocks. Anser denne som løst.
