### ISSUE TITLE
Bedre brukeropplevelse for helt ferske kodere

### ISSUE THREAD

**Issue by tjesi** [kodeklubben/oppgaver#175]
vi (eg & @tawaterhouse) ønsker en bedre kobling mellom kidsakoder og githubsidene for å gjøre det enklere og bedre for brukere å finne og bruke oppgavesettene våre. altså, vi fortsetter å utvikle githubsidene som vi har gjort til nå. for alle avanserte brukere og de som er kjent med sidene så er de helt topp. men for nybegynnere/lærere/foreldre ++ så har vi fått noen tilbakemeldinger om at det ikke alltid er like lett å navigere.

vi er altså ute etter en enklere måte å finne oppgavesettene på via kidsakoder.no, og når vi prøvde embeddig med iframe i høst så ble ikke det særlig bra - og vi valgte å ikke gå videre med det.

et forslag er å lage egne sider for kursoversikt og oppgaveoversikt på kidsakoder, men ved å trykke på selve oppgavesettet så sendes de til github. sjekk eksempel på http://www.kidsakoder.no/koding/.

hva tenker dere andre om dette?

![image](https://cloud.githubusercontent.com/assets/5648743/13044785/63af807c-d3d0-11e5-8aa8-330865dd3dc0.png)

![image](https://cloud.githubusercontent.com/assets/5648743/13044792/6cce7834-d3d0-11e5-963f-568c419c6bec.png)

**Comment by arve0** [comment]
> vi (eg & @tawaterhouse) ønsker en bedre kobling mellom kidsakoder og githubsidene for å gjøre det enklere og bedre for brukere å finne og bruke oppgavesettene våre.

Knappen til LKK er forsvunnet etter mergingen av #173, denne kan vi legge tilbake, som en start.

> men for nybegynnere/lærere/foreldre ++ så har vi fått noen tilbakemeldinger om at det ikke alltid er like lett å navigere.

Kanskje du har svar på noen av disse? Jeg trur de vil være meget relevant på hvilken avgjørelse som tas:
- Hva er de konkrete tilbakemeldingene? 
  - Hva kan forbedres?
  - Er det noen lette fiks vi kan starte med?
- Hvor mange tilbakemeldinger er det snakk om?
  - Hvor mange brukere er det av kidsakoder og kk.github.io per nå (google analytics)?

> vi er altså ute etter en enklere måte å finne oppgavesettene på via kidsakoder.no

En umiddelbar tanke, endre lenken fra "Lær koding her!" til "Oppgaver". Min subjektive assosiasjon for "Lær koding her" er "Finn kodeklubb".

> et forslag er å lage egne sider for kursoversikt og oppgaveoversikt på kidsakoder, men ved å trykke på selve oppgavesettet så sendes de til github. sjekk eksempel på http://www.kidsakoder.no/koding/.

Ved videreutvikling av kidsakoder.no anbefaler jeg at dere tenker på "feature bloat". Per i dag bruker kidsakoder over 2 sekund å laste hos meg. Siden henter 77 ressurser.

![kidsakoder_lastetid](https://cloud.githubusercontent.com/assets/4810521/13047715/5a610962-d3e1-11e5-8bdb-c6a95213490d.PNG)

Til sammenligning bruker kk.github.io cirka 0,5 sekund og har 23 ressurser.

![kk gihub no_lastetid](https://cloud.githubusercontent.com/assets/4810521/13047738/8627c644-d3e1-11e5-9352-c651f25bdd83.PNG)

**Comment by perry-** [comment]
Per dags dato har vi ingen byggeoppgaver som transformerer CSS og JS i kidsakoder.no-prosjektet, det er noe vi kunne sett på for å få kortet ned lastetiden. Jeg tror nok uansett at noe av lastetiden påvirkes av ting utenfor vår kontroll, da mye styres av WordPress. Jeg er litt usikker på hvordan man eventuelt legger inn f.eks. gulp/webpack i WP-miljøet.

@tjesi: Vi kan godt legge til lenker til de respektive oppgavesettene i WordPress, kanskje noe man også kan gjøre redaksjonelt / via admingrensesnittet?

**Comment by tawaterhouse** [comment]
Vi har ikke talt tilbakemelding på dette, men det er mye i mange former, bla på alle kodearr hvor folk ikke er kjent med det. Helt kort er Github bra hvis du er kjent der og vet hvor du skal klikke for å finne noe, ellers er det katastrofe for tilfeldige folk som skal navigere seg frem til noe, feks må man i praksis åpne veiledningen for å finne ut av om den kan passe.

Det er vi tenker er å representere hver veiledning på kidsakoder.no med noe mer informasjon enn det lar seg gjøre å vise frem på Github, ref. bilde @tjesi la ved, og linke rett til veiledningen. Github vil ikke bli berørt .

I tillegg er det nok et poeng å bruke en mal pr "språk" på Github slik at den kan inneholde link tilbake til rett kategori etc på kidsakoder.no, relevante downloads, etc uten at det må gjøres ekstra arbeid med slikt for hver nye veiledning.

Det innebærer at arbeidet med veiledninger på Github ikke påvirkes, men at vi styrer brukere til dem via et mer hensiktsmessig grensesnitt på siten de allerede er på.

> Er det noen lette fiks vi kan starte med?

Dette er en quickfix i seg selv, i tillegg vil det også redusere vedlikehold og ekstraarbeid med alt som ikke er veiledninger på Github.

**Comment by gahjelle** [comment]
Umiddelbart er jeg litt skeptisk, fordi om jeg forstår det riktig vil det ikke være autogenererte sider på kidsakoder.no det er snakk om? I såfall løper vi fort inn i et vedlikeholdsproblem, hvor for eksempel nye oppgaver mangler på kidsakoder.no, forbedringer i introteksten er ikke oppdatert på kidsakoder.no (eller omvendt). Veiledninger vil da måtte vedlikeholdes et annet sted enn oppgavene og det blir det fort kaos av.

Personlig tror jeg en bedre løsning er å videreutvikle github-sidene. Vi har allerede flere ganger diskutert å legge til lærerveiledninger. Noen enkle slike er også allerede skrevet (se f.eks. https://github.com/kodeklubben/oppgaver/blob/master/src/scratch/labyrint/README.md), men ikke gjort lett tilgjengelige.

Å legge til introduksjonen fra oppgaven som over, eller en separat veileder-innledning, på oppgavesiden tror jeg ikke skal være en voldsom oppgave (@arve0, håper jeg ikke misinformerer i min naivitet). Den kan entes vises som i eksempelet deres, eller gjøres collapsible eller med en mouse-over, alt etter hva vi finne mest hensiktsmessig. Kanskje ha en `jeg er veileder`-knapp som skrur på og av visningen av disse?

I forhold til finnbarhet av siden tror jeg forslaget til Arve er bra: Kall lenken **Oppgaver** i stedet for **Lær Koding Her**. Videre kan vi lenke for eksempel nettadressen oppgaver.kodeklubben.no til kodeklubben.github.io for å få en snillere adresse (vi har også allerede kidsakoder.no/koding). Og det er jo også mulig å style oppgavesidene slik at de blir likere kidsakoder.no.

**Comment by gahjelle** [comment]
Helt konkret: Er det at siden kodeklubben.github.io er vanskelig å finne dere får mest tilbakemelding på, eller at etter at man har kommet til kodeklubben.github.io så er det vanskelig å finne en passende oppgave? Eller begge deler? Eller noe annet?

**Comment by arve0** [comment]
@perry- Dersom WP er tregheten, er kanskje cache en enkel forbedring? (Gitt at den i dag gjør DB-oppslag for hvert treff?)

@tawaterhouse Forslagene dine høres rimelige ut og burde være mulig å få til. Umiddelbart tenker jeg at fordelen med å gjøre det i WP er redigeringsmuligheten, som er mer menneskelig? Fordelen med å gjøre det på github er at alle (ikke bare sentrale personer) kan editere og fikse ting i åpenhet. Nettverkseffekten er ganske tydelig; dersom man ser på statistikken er det [seks personer har deltatt](https://github.com/kodeklubben/oppgaver/pulse/monthly) "frivillig" den siste måneden og [totalt siden 2013](https://github.com/kodeklubben/oppgaver/graphs/contributors) 32 bidragsytere.

Med tanke på samarbeid (og revideringspraksisen vi følger), tror jeg ikke WP skalerer like bra.

Uansett hvilken vei man går, så tenker jeg det er opplagt at dette må autogenereres, som @gahjelle nevner.

**Comment by arve0** [comment]
@gahjelle Introduksjon på `:hover` burde være lett å fikse (det er i praksis det vi gjør på søket).

**Comment by tawaterhouse** [comment]
Vil understreke at det vi snakker om er å legge et lag med informasjon og linker på kidsakoder.no i en mer "vanlig" bruker/person vennlig format, innpakking, etc enn det github "leverer". Ikke flytte oppgaver, endre måten det jobbes med oppgaver, påvirke hvem som kan jobbe med oppgaver, etc. Vi snakker altså om å presentere i en kontekst som er mer umiddelbar, lettere tilgjengelig (ikke url etc), lettere å tilpasse og gjøre endringer i etc veien frem til selv oppgaven/veiledningen. I mangel av et bedre case å peke på snakker vi altså om et bittelite mini Yahoo med grupperte linker, ikke med lange veildinger til oppgaver/linker, men med litt standardisert tekst ved hver enkelt.

Jeg er ikke bekymret for arbeidsmengde eller mulighet til å i praksis oppdatere. Pr i dag tror jeg ikke det er mulig og/eller noe særlig enkelt å automatisere en evt integrasjon/kobling. Jeg ser heller ikke noe stort behov iom, hadde vært fint, men fremstår ikke som viktig eller i stor grad effektiviserende.

Det er i hovedsak tre scenarier for at det må skje noe på kidsakoder.no om vi skal lenke opp derfra (og igjen så minner jeg om at det evt i praksis (egentlig) ikke vil påvirke noe som skjer her):

1. nye oppgaver her vil måtte lenkes opp, en evt liten forsinkelse på det vil evt være av minimal betydning.
2. betydelig endring av beskrivelse vil kunne påvirke en evt beskrivelse på kidsakoder.no, samtidig er det vi diskuterer å tydeligere få frem nivå, hva du evt trenger, utstyr det kan gjøres med (pc vs tablet etc), osv. Det er vanskelig å se for seg at dette skulle endres så dramatisk at det er av noe særlig betydning.
3. oppgaver slettes her, skjer vel heller ikke så ofte at det fremstår som noen stor barriere. 

Om en oppgave justeres, feilrettes, for litt bedre forklaeringer, et nytt bilde etc forblir url-en til oppgaven/veiledningen den samme og og det er heller ikke noe som evt må gjøres på kidsakoder.no for å at den siste versjonen skal være linket opp. Jeg klarer altså ikke se hvordan revideringspraksis (etc) her hverken er i veien for å gjøre dette, eller skulle bli påvirket av det.

Jeg kan ikke se at dette i realiteten påvirker, eller begrenser muligheten til å jobbe her, vil påvirke antallet som kan jobbe her, hvor åpent eller ikke det gjøres etc. Mao. (den meget gode) jobben som skjer her trenger ikke bli påvirket på noe vis av at vi evt lager et "veikart" til oppgavene/veiledningene her på kidsakoder.no

Faktisk opplever jeg det heller som "motsatt", vi snakker å om å gjøre det enklere å finne frem til det reelle innholdet her, oppgavene/veiledningene. Om noen ønsker, prefererer, etc å navigere i universet her vil jo det være like tilstede som i dag, men det vil være "en vei hit" som fungerer bedre for mange.

**Comment by tawaterhouse** [comment]
Når det gjelder innspillene om kidsakoder.no, opplagt & spot on...

Det er helt sikkert mye som kan gjøres med optimalsering for å forbedre last og annet. Det er også mye som kan tunes & tweakes med språk i menyer og ellers.

**Comment by tawaterhouse** [comment]
> Helt konkret: Er det at siden kodeklubben.github.io er vanskelig å finne dere får mest tilbakemelding på, eller at etter at man har kommet til kodeklubben.github.io så er det vanskelig å finne en passende oppgave? Eller begge deler? Eller noe annet?

ikke vanskelig å finne, eller i det minste ikke noe vanskeligere enn annet vi har...

Utfordringene ligger i selve github-siten, intern navigasjon der, etc.

Merk dette handler ikke om oppgavene/veiledningene, men veien og ikke minst informasjonsmulighetene på veien fra http://kodeklubben.github.io/ til feks http://kodeklubben.github.io/aa-kodetimen/scratch/kodeklubben.html

**Comment by perry-** [comment]
@arve0: Jeg kjenner ikke godt nok til WP til å si noe om det, men det finnes nok helt sikkert muligheter for caching og andre ting vi kan gjøre for å optimalisere. Kan undersøke litt og se hva vi får gjort

**Comment by tawaterhouse** [comment]
>sikkert muligheter for caching og andre ting vi kan gjøre for å optimalisere

Det er det alltid, om jeg husker riktig er det i hovedsak forsiden dette er en issue? I såfall er det nok en del å hente på hvordan den er bygd opp...

det som mos def vil ha en positiv effekt er å flytte til en dedikert WPserver som er inn the making as we speak...

**Comment by arve0** [comment]
> I mangel av et bedre case å peke på snakker vi altså om et bittelite mini Yahoo med grupperte linker, ikke med lange veildinger til oppgaver/linker, men med litt standardisert tekst ved hver enkelt.

Ser utkastet til Tjerand har brukt introduksjonen på oppgaven. Er det samme som er tenkt for resten, eller er det nye introduksjoner som skal skrives? Kanskje skrive en samlet introduksjon for noen oppgaver (ettersom det totalt er ~140 oppgaver)?

> Pr i dag tror jeg ikke det er mulig og/eller noe særlig enkelt å automatisere en evt integrasjon/kobling.

Hvis vi skal bruke introduksjonen til oppgaven (som jeg syns er en god idè), burde det være nokså enkelt å hente disse ut (om ønskelig). Integrasjon med WP burde ikke være så vanskelig heller.

> Jeg kan ikke se at dette i realiteten påvirker, eller begrenser muligheten til å jobbe her...

Dersom introduksjonen til oppgaver forbedres, tenker jeg det er smart å få dette med i toppen av oppgavene også.

> Utfordringene ligger i selve github-siten, intern navigasjon der, etc.

Vi får prøve å forbedre dette også.

> Merk dette handler ikke om oppgavene/veiledningene, men veien og ikke minst informasjonsmulighetene på veien fra http://kodeklubben.github.io/ til feks http://kodeklubben.github.io/aa-kodetimen/scratch/kodeklubben.html

Mitt synspunkt er at informasjonen under kodetimen ikke er oppgaver (unntaket er [Mine robotvenner](http://kodeklubben.github.io/aa-kodetimen/robotvenner/robotvenner.html)), men veiledninger. De burde vært på kidsakoder.no og lenket til kk.gihub.io, slik som @tawaterhouse beskriver; *femto yahoo*.

> det som mos def vil ha en positiv effekt er å flytte til en dedikert WPserver som er inn the making as we speak...

:+1: Hvis ytelsesforbedringer er på vei, så er det et ikke-tema i denne sammenheng.

Se også [meningsmålingen](https://www.facebook.com/groups/996312967052695/permalink/1263919586958697/?qa_ref=qd) på facebook.

**Comment by gahjelle** [comment]
Jeg får inntrykk av at ikke alle vet at vi (dvs @arve0 utvikler denne in the open) har full kontroll på hvordan github-sidene utformes. Med andre ord, dersom folk har et problem med å navigere fra forsiden på kodeklubben.github.io til oppgaver så bør vi forbedre github-sidene slik at alle kan dra nytte av endringene. Ikke bare de som (tilfeldigvis?) kommer fra kidsakoder.no.

Kodetimen-oppgavene (enig med Arve i at disse stort sett ikke er oppgaver, bare pekere/veiledere videre) er ganske spesielle så om det er spesielt disse vi får tilbakemelding på er det nyttig informasjon? Disse er jeg enig i at gjerne passer bedre inn direkte på kidsakoder.no.

Men jeg ser ingen verdi i å prøve å gjenskape oppgavelisten fra github på kidsakoder.no. Det vil skape vedlikeholdsproblemer. Alt man ønsker å gjøre på kidsakoder kan man gjøre (ofte lettere) på github. Og vi må forholde oss til at brukere har to forskjellige brukeropplevelser når vi skal hjelpe dem med ting.

**Comment by tawaterhouse** [comment]
Poll/vote på Facebook er noe annet enn det vi diskuterer, og er ut til å være gode ideer som burde kunne implementeres på et eller annet vis.

Det vi diskuterer her er en enklere vei til oppgavene enn vi har i dag, det er flere årsaker til dette, den viktigste er at vi hele tiden må søke å legge lista på et nivå som gjør at folk ikke trenger å bruke motivasjon, tid, etc på å finne oppgaver som passer for dem.

En annen årsak er at vi selvsagt skal skille mellom de som lager og de som bruker en oppgave/veiledning/kall det hva du vil.

Vi snakker altså om å forenkle veien til oppgavene fordi dette ikke bare handler om å nå mange, men også om å gjøre det lett å nå dem, unngå barriærer, unngå at folk må be om hjelp for å finne oppgaver etc.

I dag har vi brukerorientering på teknologien/teknologens premisser, et av de neste forbedringspunktene våre er å gå til brukerorientering på brukeres premisser, spesielt de brukerene som har minst erfaring med (mye av) det vi driver med.

(har i praksis skrevet det samme på facebook...)

**Comment by kwrl** [comment]
Ikke for å dra diskusjonen videre off topic, men kan skyte inn at det å sette opp wordpress bak [varnish](https://www.varnish-cache.org/) kan gi ganske ville ytelsesforbedringer. Det kan gjerne kombineres [W3 Cache](https://wordpress.org/plugins/w3-total-cache/). Wordpress ofte tregt i utgangspunktet, men mye kan forbedres mye ved hjelp av caching. 

Da jeg lastet kidsakoder.no i sted hadde jeg en TTFB(time to first byte) på 800ms, noe som er ganske krise. Når jeg pinger serveren så får jeg svar på under 50ms. Det er med andre ord lite av de 800ms som er grunnet nettverk.

Når dette er sagt så kan jeg prøve å hive meg på den ordentlige diskusjonen. Jeg kan ikke sies å ha bidratt mye til vedlikeholdet av hverken kodeklubben.github.io eller kidsakoder.no, men jeg er også noe skeptisk til å duplisere vedlikeholdsarbeidet av oppgaveoversikten. Jeg har alltid likt tanken om å lage ett produkt som fungerer bra, fremfor to som fungerer nesten bra. Hvis det er problemer med å navigere internt på kodeklubben.github.io så burde forsiden der forbedres, vi burde ikke lage enda en forside.

**Comment by tawaterhouse** [comment]
serven vi er på nå skal vi bort fra, blir en fin dag...

**Comment by arve0** [comment]
> Poll/vote på Facebook er noe annet enn det vi diskuterer, og ser ut til å være gode ideer som burde kunne implementeres på et eller annet vis.

Forslagene er kanskje utenom vårt emne ja, om fokus er komplette nybegynnere.

> Det vi diskuterer her er en enklere vei til oppgavene enn vi har i dag, det er flere årsaker til dette, den viktigste er at vi hele tiden må søke å legge lista på et nivå som gjør at folk ikke trenger å bruke motivasjon, tid, etc på å finne oppgaver som passer for dem.

Her er to forslag:
1. Skriv en bedre introduksjon på førstesiden.
2. Endre introduksjonsguiden direkte til en oppgave som det passer å starte med. (Åpne kodeklubben.github.io i ikognitomodus om du har glemt hvordan førstebruker introduseres til siden).

> En annen årsak er at vi selvsagt skal skille mellom de som lager og de som bruker en oppgave/veiledning/kall det hva du vil.

Mener du lærer/elev? Regner med de som lager oppgaver klarer å navigere seg rundt?

> Vi snakker altså om å forenkle veien til oppgavene fordi dette ikke bare handler om å nå mange, men også om å gjøre det lett å nå dem, unngå barriærer, unngå at folk må be om hjelp for å finne oppgaver etc.
I dag har vi brukerorientering på teknologien/teknologens premisser, et av de neste forbedringspunktene våre er å gå til brukerorientering på brukeres premisser, spesielt de brukerene som har minst erfaring med (mye av) det vi driver med.

Om forslagene ovenfor ikke passer, kom gjerne med konkrete forslag til hvordan vi kan tilrettelegge for brukerne med minst erfaring.

**Comment by arve0** [comment]
Har gjort noen endringer i "navigasjon" av github-siden, se https://github.com/arve0/codeclub_lesson_builder/pull/189.

**Comment by arve0** [comment]
Her er noen forslag fra @gahjelle:

- [ ] To moduser, verbose og kompakt. Verbose som default, som viser mer informasjon/tekst tilrettelagt for nye brukere. Veksler med en knapp i UI.
- [ ] Tematisk og tekniske tagger.
- [ ] Lærerveiledninger for både oppgaver og kurs.
- [ ] Begrenset søk, feks bare intro-oppgaver, kodespråk/kurs, kobling til skolefag.
- [x] Hover for oppgaver.
- [x] Hover for kurs.
- [ ] Bedre sortering av oppgaver. Virker som det er noe tilfeldig per nå.
- [ ] Flytt kodetimen over til kidsakoder.no
- [ ] Introduksjon på førstesiden med knapper for nybegynnere. "Start med Scratch" -> direkte til oppgave, osv.
- [x] Mulighet for å gi tilbakemelding på hver oppgave.
- [ ] Forbedre tilbakemeldingen, slik at github-konto ikke er nødvendig.
- [x] Sortering av kurs etter antall oppgaver i kurset.

**Comment by arve0** [comment]
Lukker denne, siden diskusjonen har stoppet opp.

I følge statistikken har vi økt gjennomsnittlig tid på side og sidedybde etter oppdateringen, men også fluktfrekvens.

### 1. januar - 25. februar
<img width="574" alt="atferd_1jan_25feb" src="https://cloud.githubusercontent.com/assets/4810521/14652126/353135a8-0673-11e6-81fa-860de5c367c3.PNG">
<img width="444" alt="sidedybde_1jan_25feb" src="https://cloud.githubusercontent.com/assets/4810521/14652131/38dc2fc8-0673-11e6-99a9-a9c5d7b4e2b9.PNG">

### 25. februar - 15. april
<img width="579" alt="atferd_25feb_15april" src="https://cloud.githubusercontent.com/assets/4810521/14652149/51e3f67c-0673-11e6-8230-a62ed3a108c2.PNG">
<img width="431" alt="sidedybde_25feb_15april" src="https://cloud.githubusercontent.com/assets/4810521/14652163/5bb6bf36-0673-11e6-982e-8d151e4a8080.PNG">
