### ISSUE TITLE
Straffespark: måtte legge inn vent for å få variablene til å telle opp

### ISSUE THREAD

**Issue by sisomm** [kodeklubben/oppgaver#181]
Plattform: PC
Browser: Chrome

I oppgaven står det "stopp alle script" og det gjør at variablene Mål og Redninger ikke blir endret med en. Jeg la inn en liten vent (på forslag fra 13-åringen, hehe) og da virket det. Men det blir jo litt komplisert? 
![straffespark](https://cloud.githubusercontent.com/assets/4808844/13330186/ec6ce448-dbf7-11e5-9c93-8c2c4f661bf0.PNG)

**Comment by sisomm** [comment]
ÅÅÅH jeg ser løsningen! Man kan ha EN "Jeg mottar "Mål" og så FØRST endre variablen og SÅ stoppe de andre scriptene. Da blir det logisk og man slipper vent

**Comment by arve0** [comment]
Da blir #183 feil..

**Comment by gahjelle** [comment]
Hehe ... 

jeg tror den "offisielle" løsningen er at skriptene som endrer mål og redning ligger på scenen, hvor skriptene ikke stoppes.

![image](https://cloud.githubusercontent.com/assets/728076/13332021/548107a0-dc00-11e5-91ef-fb8c523c6022.png)

Men å legge dem sammen i et skript burde også funke fint! :smile:

**Comment by gahjelle** [comment]
Har beskrevet utfordringen med å legge skriptene på riktig figur i den ferske lærerveiledningen for Straffespark (#184). Lukker derfor denne.

Takk for tilbakemeldingen, @sisomm!
