### ISSUE TITLE
Scratch: Enarmet banditt

### ISSUE THREAD

**Issue by kwrl** [kodeklubben/oppgaver#192]
<img width="456" alt="screen shot 2016-02-28 at 11 56 04" src="https://cloud.githubusercontent.com/assets/2329811/13378796/4f8dc24c-de12-11e5-8033-58eb7bf674b1.png">

En style class som ikke blir parset skikkelig her. Første steg på sjekklisten under punkt 3.

**Comment by arve0** [comment]
Er nok et mellomrom etter ` og før {
