### ISSUE TITLE
gjør web-oppgavene ferdige

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#21]
Det er påbegynt arbeid på å lage oppgaver som handler om web, men disse er ikke ferdige og ikke publisert på kodeklubben.github.io enda.

**Comment by famthegeek** [comment]
Hva er det som trengs å gjøres med web oppgavene før de kan publiseres?

**Comment by arve0** [comment]
Hei Fredrik!
Det som trengs gjøres er:

- Bestemme vanskelighetsgrad mellom [1 til 6](https://github.com/arve0/codeclub_lesson_builder/blob/master/config.js#L49-55) på alle oppgaver. Eks: `level: 1` blant [YAML-taggene](https://github.com/arve0/codeclub_lesson_builder/blob/master/FORMAT.md#yaml-header).
- Lage en spilleliste som rangerer oppgavene i en passelig rekkefølge for et kurs.
- Kvalitetssikre alle oppgavene:
  - Korrekturlesning
  - Sjekk at oppgavene er bygd opp på lik vis (steg overskrift, intro, små gjøremål...). 
  - Sjekk at markdown er riktig formatert, altså fiks slike feil som denne:

  ![skjermbilde 2015-07-21 kl 15 20 51](https://cloud.githubusercontent.com/assets/4810521/8801631/5bfe664e-2fbc-11e5-9c48-6d4266686ae9.png)

Så fremst jeg vet, er oppgavene oversatt fra [CodeClubUK](http://projects.codeclubworld.org/en-GB/05_html_01/index.html), så sjekk at oppgavene er komplett oversatt og at alle oppgavene kommet med i oversettelsen. Engelsk kilde finnes [her](https://github.com/CodeClub/webdev-curriculum/tree/master/en-GB).

**Comment by famthegeek** [comment]
Jeg skal ta en titt åsså kommer det kanskje et pull request i løpet av uka kanskje

**Comment by arve0** [comment]
Supert! Del gjerne PR opp i begrensede tema. Eksempelvis, ta en oppgave om gangen.

**Comment by arve0** [comment]
@famthegeek ping

**Comment by famthegeek** [comment]
@arve0 Pong
Ting tar tid, har ikke rukket over det jeg hadde planer om enda

**Comment by arve0** [comment]
Web-oppgavene har lugget ute en stund. Vi har fått noen tilbakemeldinger, og rettet i de. Lukker derfor denne nå.
