### ISSUE TITLE
Scratch: 3D-Flakser, Del 1

### ISSUE THREAD

**Issue by dawid1309** [kodeklubben/oppgaver#218]
det er en glitch at alle starter i hjørne!

**Comment by gahjelle** [comment]
Hmm ... har du litt mer informasjon? Eventuelt en lenke til scratchprosjektet?

Hvem starter alle i hjørnet? Når?

**Comment by arve0** [comment]
Lukker denne inntil vi får mer informasjon.

**Comment by dawid1309** [comment]
jeg gjore alt som sto i instuksene men det glitcha!

**Comment by gahjelle** [comment]
Har du mulighet til å legge ut prosjektet ditt, og sende oss nettadressen / url'en til prosjektet? Slik at vi kan få litt mer info om hva som går galt?
