### ISSUE TITLE
Gjøre katalogstrukturen for Pythonoppgaver konsistent med resten

### ISSUE THREAD

**Issue by gahjelle** [kodeklubben/oppgaver#23]
På grunn av en tidligere tanke om å bruke katalogstrukturen for å si noe om vanskelighetsgraden på oppgaver ligger våre egenutviklede oppgaver i en katalog som heter `egne-enkel`. Den nye byggeren har helt fjernet dette behovet, og jeg foreslår at vi bytter litt navn på python-katalogene også (så de blir like scratch-katalogene) før alt for mange har tatt dem i bruk. Så slipper vi fremover å måtte forklare hvorfor de vanskelige oppgavene ligger i en katalog som heter enkel ...

I tillegg til at det kan være noen som har lenket direkte til de eksisterende Python-oppgavene er det også noen som har begynt å lage python-oppgaver, som også må bli gjort oppmerksom på denne endringen om vi kjører på.

Hva tror dere?

**Comment by arve0** [comment]
Haha! Tenkte akkurat åpne en issue på det samme! :+1: 

Tenkte også - trenger vi å dele inn i katalogene `egne` og `codeclubuk`? Kanskje kan vi ha en flat struktur med alle oppgavene i samme katalog? Da blir det litt enklere å finne fram når man browser på gh. Personlig synes jeg ikke det er noe galt med en katalog med 40 filer/kataloger, så lenge de kan sorteres etter navn, etc, men det er kanskje andre som er uenig?

**Comment by Helgenen** [comment]
For meg er det helt greit å slå sammen alle så lenge lisensene blir
beholdt. Det er også klarert med Code Club UK.

Mon Feb 09 2015 at 11.04.03 skrev Arve Seljebu <notifications@github.com>:

**Comment by arve0** [comment]
Lisensene er ikke noe problem, ettersom vi har lagt til author, license og logo for alle codeclub-oppgaver, som gir code club uk logo i header, samt forfatter+lisens i footer.

**Comment by gahjelle** [comment]
I like it!

Flott at du tenker enda enklere enn meg! Enig i at vi ikke trenger egne/ukcodeclub oppdelingen, siden denne informasjonen er ivaretatt i headeren uansett.

Vi burde gjøre samme utflatingen på computercraft, web  og scratch-oppgavene også. På web-oppgavene bør vi endre litt på oppgavekatalognavnene. Jeg kan godt lage en issue på det siste, og fikse den selv (evt ta det som en underdel av den issuen vi allerede har på weboppgavene)

**Comment by arve0** [comment]
Legger ved en par ekstra commit med cc, web og scratch. 2 sek.

**Comment by arve0** [comment]
Fikset i #24
