### ISSUE TITLE
LearnToMod: Screenshots Bygge en kube

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#257]
Noen av skjermbildene til [Bygge en kube](http://kodeklubben.github.io/learntomod/bygge_en_kube/bygge_en_kube.html) er såpass komprimert at de er vanskelig å lese. Man trenger Learn To Mod-konto for å fikse dette.

Fiks:
- [ ] Lag PNG-skjermbilder.

**Comment by tjesi** [comment]
@PaulSolheim har du mulighet til å oppdatere bildene?
