### ISSUE TITLE
Hide multiline

### ISSUE THREAD

**Issue by larsfk** [kodeklubben/oppgaver#264]
Jobber med å oppdatere/oppgradere og lage nye oppgaver til Web og jeg skulle så gjerne hatt muligheten til å gjemme kode. Er det mulig å få til å gjemme noe som dette:

<toggle>
  **Hint**
  <hide>
```html
<!doctype html>
<html>
  <head>
    <title> Katten Felix er forsvunnet </title>
  </head>
  <body>
    <h1>Forsvunnet</h1>
    <h2>Katten Felix</h2>
  </body>
</html>
```
  </hide>
</toggle>

**Comment by gahjelle** [comment]
Noe som dette? 

https://github.com/arve0/codeclub_lesson_builder/pull/171

**Comment by larsfk** [comment]
Ja, men det fungerer ikke hos meg...

**Comment by arve0** [comment]
Har du en branch med kode, så det kan reproduseres?

**Comment by larsfk** [comment]
Prøver dette: 
<toggle>
  **Hint**
  <hide>
```html
<!doctype html>
<html>
  <head>
    <title> Katten Felix er forsvunnet </title>
  </head>
  <body>
    <h1>Forsvunnet</h1>
    <h2>Katten Felix</h2>
  </body>
</html>
```
  </hide>
</toggle>

Og har prøvd med bare en linje også, men da står det bare Hide med fet-skrift

**Comment by arve0** [comment]
Aha. Du kan bruke `<pre>` her på github for å unngå formateringen. Skal teste ut nå, 2 sek.

**Comment by larsfk** [comment]
<pre>
<toggle>
  **Hint**
  <hide>
```html
<!doctype html>
<html>
  <head>
    <title> Katten Felix er forsvunnet </title>
  </head>
  <body>
    <h1>Forsvunnet</h1>
    <h2>Katten Felix</h2>
  </body>
</html>
```
  </hide>
</toggle>
</pre>

**Comment by arve0** [comment]
Hehe, ser ut som det ikke gikk 😆

**Comment by larsfk** [comment]
Stemmer det :P Kan man laste opp bilder her?

**Comment by larsfk** [comment]
![skjermbilde 2016-07-04 kl 10 26 00](https://cloud.githubusercontent.com/assets/5544621/16554851/bd0f5196-41d1-11e6-8d34-9fa194ac85aa.png)

**Comment by arve0** [comment]
Det er pga kodeblokken, skal se om det kan fikses.

**Comment by arve0** [comment]
Grunnen til at dette skjer, er at markdown parser tolker

```html
<toggle>**Hint**
  <hide>
```

som en paragraf og ikke en html-blokk på grunn av `**Hint**`.

Du kan komme rundt dette med den ekvivalente:

```
<toggle>
  <strong>Hint</strong>
  <hide>

```html
<!doctype html>
<html>
  <head>
    <title> Katten Felix er forsvunnet </title>
  </head>
  <body>
    <h1>Forsvunnet</h1>
    <h2>Katten Felix</h2>
  </body>
</html>
``\`  <-- unngå github parsing

  </hide>
</toggle>
```

Det blir seende litt rart ut, men kanskje ok nok?
![hide code block](https://cloud.githubusercontent.com/assets/4810521/16555851/0935e7ec-41d7-11e6-88fb-efe7894c7443.gif)

**Comment by larsfk** [comment]
Perfekt det der! Takk sjef! :D

**Comment by arve0** [comment]
Ser ut som du fikk til, så lukker denne.
