### ISSUE TITLE
Kategoriene i et oppgavesett

### ISSUE THREAD

**Issue by larsfk** [kodeklubben/oppgaver#266]
Er det mulig å endre kategoriene eller nivåene i ett spesifikt oppgavesett uten at det påvirker resten? Skulle gjerne hatt andre kategorier i "Web" :)

**Comment by arve0** [comment]
Du kan lage spillelister og gjemme filene fra Introduksjon, Nybegynner, etc med `indexed: false`. Spillelisten kan du kalle hva som helst, feks "Web kurs 1". [Les mer om spillelister](https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/playlists).

**Comment by larsfk** [comment]
Eks: 
I "Web" så vil jeg heller ha følgende kategorier: "HTML", "CSS", "Javascript". Men kan jo bare legge dem i egne spillelister dersom det er enklere :)

**Comment by arve0** [comment]
To andre forslag:
1. Legg til kategorien i tittelen: `title: Løpsk YouTube teller [JavaScript]`
2. Lag egne kurs (men dumt å fragmentere oppgaver under samme tema)

**Comment by larsfk** [comment]
Tanken var å at de 3 kategoriene bygger på hverandre og at det da gjør det oversiktelig ved å ha en slik inndeling, men jeg kjører det i Tittelen + lager spillelister og ser hvordan det blir

**Comment by arve0** [comment]
Lukker denne, ettersom du har brukt "Tema: Tittel" i web-oppgavene.
