### ISSUE TITLE
Web: enkel måte å dele nettside

### ISSUE THREAD

**Issue by larsfk** [kodeklubben/oppgaver#272]
Vi har en oppgave per i dag under oppgaven "En hjemmeside" et steg som heter "Publiser nettsiden din på Internett (ekstra aktivitet)". Denne jobber jeg med å få til å bli en egen oppgave. Her er det forklart hvordan man får en nettside publisert ved hjelp av Dropbox og Google Drive. Det finnes bedre måter å gjøre dette på, men etter å ha diskutert litt med Arve så leter vi etter en måte å gjøre dette uten å måtte logge seg inn.

Noen forslag? 

Prøvd jsfiddle, jsbin, men syntes ikke de fungere så bra til dette. 
https://thimble.mozilla.org/en-US/ virker ganske bra, men da trenger man en bruker.

**Comment by arve0** [comment]
https://bl.ocks.org/-/about

**Comment by arve0** [comment]
https://surge.sh
https://pages.github.com

Se også #280, allerede noen som synes oppskriften er vanskelig.

**Comment by larsfk** [comment]
Surge.sh og pages.github.com er litt for viderekommende syntes jeg så foreslår å dele oppgaven inn i jsbin for "nybegynnere" og surge og pages.github for viderekommende. Eller kanskje bare bruke pages.github?

**Comment by ArgTang** [comment]
alternativ til jsbin/jsfiddle er codepen.io

**Comment by larsfk** [comment]
Codepen.io: kan lagre side gratis uten å måtte lage bruker, men kan ikke dele siden med en annen uten å vise kildekoden. Kan hende det går, men jeg har ikke klart å finne ut av det enda.

**Comment by ArgTang** [comment]
ah nei, tror ikke det går, en kan få full page, men codepenmenyen er der fortsatt.

tror nok github pages er det enkleste da. En kan jo introdusere git-GUI som sourcetree eller gitKraken, evt for simple prosjekter funker også github sin git klient. 
Azure er også veldig lett med git, men da trenger en to kontoer en for en eller annen git-host og en for azure.

**Comment by larsfk** [comment]
Vi går for github pages og øker nivået på oppgaven. Setter meg ned å jobber med den nå fremover denne uka.

**Comment by arve0** [comment]
Fikset i #280
