### ISSUE TITLE
nb-NO -> src, eget codeclub uk upstream repo

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#28]
Foreslår at vi flytter `nb-NO` tilbake til `src` siden dette skaper problemer når vi bytter branch på codeclub_lesson_builder. Det er mulig å bruke symbolsk lenke, men det er [knot å forklare](https://gitter.im/kodeklubben/oppgaver?at=54d7e302a529fda251c0a7c4).

Hvis jeg forstod deg riktig, @gahjelle, ønsket du ha oppgavene i `nb-NO` slik at det skulle bli lettere å sende oppgavene opp til code club uk? Foreslår derfor samtidig at vi lager et repo for dette med kode som konverterer oppgavene våre til ccuk-format, så blir denne problematikken *"unna vei"* for ferske bidragsytere.

**Comment by gahjelle** [comment]
Hei, 

tanken min var litt bredere enn bare til Code Club UK (for disse løses nok enklest på andre måter uansett). Jeg tenkte mer at det hadde vært moro om vi i Norge kunne bidratt med oppgaver som kan brukes også ellers i verden, og ved å lage engelske oversettelser av ihvertfall noen av våre egenutviklede oppgaver ville de blitt mye mer tilgjengelige.

Men, veldig enig i at brukervennlighet for bidragsyterne bør trumfe det meste, og dagens løsning er litt knotete. Flytt derfor gjerne `nb-NO` tilbake til `src`.

Jeg har noen tanker rundt et annet opplegg for oversettelser (si ifra om du mener det er bedre å flytte dette til et eget issue):

+ Alt ligger i `src/språk/oppgave`-struktur som nå
+ Vi bruker language-feltet i yaml-headeren for å si hvilket språk en oppgave er skrevet på
+ Byggeren bygger alle oppgaver/språk den finner, men lager en index for hvert språk. Man kan for eksempel bytte mellom språk vha små flaggikoner øverst til høyre på den grønne menylinjen på forsiden.
+ Filnavn kan jo være omtrent hva som helst siden disse ikke vises noe sted (utenom i sortering), men foreslår at vi legger til en språkindikator mot slutten av filnavnet for at vi lett skal få oversikt selv. For eksempel `scratch/straffespark/straffespark.md` kan bli oversatt i filen `scratch/straffespark/penalty_kicks_en-GB.md` og `scratch/pong/pong.md` kan bli oversatt i filen `scratch/pong/pong_en-GB.md`.
+ Det ville vært kult å også ha flagg på selve oppgavesidene for å gå til samme oppgave på et annet språk. Det er jo trivielt der vi bare har en oppgave per katalog, men blir litt mer tricky der en oppgave er delt i flere deler (som for eksempel `hvor_i_all_verden`). Kan vel uansett løses med noen enkle heuristics.
+ Vi må også tenke på hvordan spillelister løses i et slikt system, men det får vi til.

Hva tror dere? En slik løsning tror jeg vil være enklere for bidragsyterne å komme igang med. Samtidig beholder vi muligheten til å lage oversettelser. Det vil bli litt rotete om vi plutselig får mange oversettelser, og for eksempel katalognavnet `straffespark` gir ikke så mye mening for en engelsk- eller spansktalende. Men disse to bekymringene ligger litt utenfor det scope't jeg ser for meg for dette.

**Comment by arve0** [comment]
Der traff du alle spikrene *mitt* på hodet! Foreslår vi bruker denne tråden til å diskutere videre. Jeg tar punktene dine i samme rekkefølge:

1. Enig. Det er enkelt. Ingen magi. Søk fantes på versjon 1 av AT&T UNIX.
2. Enig. Kanskje lager vi en konfigurasjonsfil også, som definerer standard YAML-tags.
3. Dersom vi bruker original-navn på mappe(eks engelsk for de som er oversatt), og tittelnavn på `.md` er oppgavene lett å finne. Å legge til språkkode skader ikke, men vet ikke om det burde være et *krav* dersom de har forskjellig tittel. Det er enkelt nok å traversere alle mapper for å finne relasjoner mellom språk (gitt at en oppgave ligger i en mappe).
4. Som nevnt i 3, dersom vi traverserer alle oppgaver og lager et relasjons-objekt, er dette enkelt å legge til.
5. Får ingen umiddelbar idè om hvordan dette løses enkelt. Hvis vi bare finner PEP20-løsningen; Lett er bedre enn sammensatt, sammensatt er bedre en komplisert.

Sender en PR på nb-NO -> src.

**Comment by gahjelle** [comment]
Hehe ... kjenner vi er veldig enige, kanskje vi må invitere inn andre som kan utfordre oss litt :stuck_out_tongue_winking_eye: 

Angående 3, enig i at det ikke skal være et krav med språkkode i filnavn. Men greit at vi har en konvensjon for hvordan skille filer som får samme tittel med forskjellig språk.

Etter å ha boblet litt ideer til spillelister i hodet: Siden hver oppgave+språk vil ha en unik url vil det være enkelt å sjekke hvilke(t) språk som er i oppgavene i spillelistene. Da kan vi bare vise spillelistene på de språksidene hvor minst en oppgave er på det gitte språket? I praksis vil vel hver spilleliste ha oppgaver på samme språk, men vi trenger jo ikke begrense byggeren til bare det.

Og om byggeren skal være internasjonal, skulle vi endret navnet `spillelister` til `playlists`. Eventuelt autodetektere spillelister ved å lete etter `.txt` filer som bare inneholder lokale pather uavhengig av i hvilke kataloger de ligger?

**Comment by arve0** [comment]
Tja, diktatur har sine fordeler..btw standarer og felleskap/samarbeid, kom over [denne](https://github.com/joyent/node/issues/5132#issuecomment-15432598). Flere gode poeng der.

Angående playlists/spillelister, så tja. Kanskje unødvendig å kalle det spillelister. Ligger i config.js nå (src branch), så enkelt endre det der.

**Comment by arve0** [comment]
@Helgenen @kwrl Tanker? :rabbit:

**Comment by Helgenen** [comment]
Jeg liker godt ideen om å kunne teste oppgaver i et annet språk, dette kan
være supernyttig i engelskundervisning f.eks. Å ha en -GB på slutten av
filnavnet kan nok være nyttig for de som for eksempel laster ned oppgavene
til eget bruk utenom github.

Jeg skjønner ikke helt hva dere mener med spillelister?

Tue Feb 10 2015 at 11.52.22 skrev Arve Seljebu <notifications@github.com>:

**Comment by arve0** [comment]
Spillelister er en samling av oppgaver som henger i lag.
https://github.com/kodeklubben/oppgaver/blob/master/nb-NO/scratch/spillelister/Kodeklubbens_kurs_1.txt

Feks kan en oppgave bruke tagen `indexed: false` og legges i en spilleliste
for å bare vises i spillelisten.

**Comment by arve0** [comment]
@Helgenen Det som diskuteres er vel om mappen skal hete spillelister eller
playlists.

**Comment by Helgenen** [comment]
Aha! Det er jo lurt. Det er fint å ha ting på norsk synes jeg, men
playlists er jo nesten norsk etterhvert. Hvor mye sannsynlig er det at
utlendinger bruker våre lister?  Er det andre i verden som har implementert
dette?

Tue Feb 10 2015 at 14.28.45 skrev Arve Seljebu <notifications@github.com>:

**Comment by arve0** [comment]
Det er ingen som bruker denne løsningen per nå. Men målet vårt er vel at
dette oppsettet skal ha så mange fordeler (enklere struktur, lettere å
komme i gang, enklere å modifisere til sitt eget bruk, etc), at den blir
tatt i bruk i andre land også.

**Comment by Helgenen** [comment]
Men da er kanskje playlists best navn?

Tue Feb 10 2015 at 14.44.16 skrev Arve Seljebu <notifications@github.com>:

**Comment by gahjelle** [comment]
Det er kanskje et poeng, som Helge illustrerer, at spilleliste-begrepet er litt kunstig i denne sammenhengen, slik at vi uansett må forklare hva det er. Og da er kanskje playlist nesten like innarbeidet på norsk (?). Navnet vi bruker i katalogstrukturen trenger jo ikke å bobles helt ut til HTMLen, der må vi jo uansett ha et system for å kunne bruke norsk tekst.

Men trenger vi egentlig å bestemme et navn på denne katalogen? Kan ikke byggeren bare lete gjennom alle kataloger og plukke ut alle filer som ser ut som en spilleliste?

**Comment by gahjelle** [comment]
Et litt annet poeng jeg tenkte på ut fra posten som startet denne tråden er at når vi har fått litt orden på ting, bør vi absolutt få sendt oversettelsene tilbake til Code Club. Det er vel en del av avtalen, og oppgavene som per nå ligger på http://projects.codeclubworld.org/nb-NO/ er ganske utdaterte og mangelfulle :)

@arve0, hadde du en tanke om at vi får gjort dette nesten automatisk?

**Comment by arve0** [comment]
Da går vi for playlists :+1: 

Automatisk, ja, kan lage en plugin for det, men det blir jo bare at spesifikasjonen blir flyttet. Altså, for å være konkret, forskjellen blir enten at vi definerer navnet [her](https://github.com/arve0/codeclub_lesson_builder/blob/src/config.js#L16) eller en algoritme inni en plugin + et [pattern](https://github.com/arve0/codeclub_lesson_builder/blob/src/gulpfile.js#L77) for gulp.

**Comment by gahjelle** [comment]
La oss gjøre det enkelt å bare bruke `playlists`-katalogen inntil vi evt oppdager behov for noe annet :)

**Comment by arve0** [comment]
@gahjelle Angående automatisk upstream, er det snakk om å legge til ting i YAML-header (feks `language: nb-NO` og `note: README.md`) og traversere alle filer og generere et [manifest](https://github.com/CodeClub/scratch-curriculum/blob/master/nb-NO/Termin-1/nb-NO_scratch_termin1.manifest).

**Comment by gahjelle** [comment]
Høres ut som en god løsning! :+1:

**Comment by arve0** [comment]
https://github.com/arve0/codeclub_lesson_builder/commit/b9056a2702fdb6ef66d5dfcef4f39f5609312dac
https://github.com/kodeklubben/oppgaver/commit/20a7cfa6804dba76a2aa8fa64fd5f8c67f32dcab

**Comment by arve0** [comment]
Laget et [repo](https://github.com/kodeklubben/upstream-codeclub) for upstream.

**Comment by gahjelle** [comment]
Jeg rekker ikke teste disse commitene (og #31) før etter møtet i kveld, men de virker fornuftige for meg. Mulig `nb-NO` var hardkodet i noen lenker i noen av scratchoppgavene og at disse må oppdateres til `src`? Jeg kan evt fikse de i kveld :)

**Comment by arve0** [comment]
Tips: Merge link-testen først, og bruk den: `gulp links`

arve0/codeclub_lesson_builder#81

**Comment by arve0** [comment]
Siden codeclub UK går bort i fra oppgaver på github (https://github.com/CodeClub/lesson_format/issues/168), er ikke denne relevant lengre.

**Comment by CodeClubRik** [comment]
Hi @arve0,

I thought it worth adding one small clarification:

It is just the lesson_format tool that is being retired. The curriculum repositories that it builds are not going away. The scratch, python and web repositories are still used as the source of our new project website.

We've added some clarification here:
https://github.com/CodeClub/lesson_format/issues/168#issuecomment-157993765

Thanks,
Rik.

**Comment by arve0** [comment]
Thanks for clarifying that, @CodeClubRik. But [your update](https://github.com/CodeClub/webdev-curriculum/commit/b44c0115c326d436299a10409a6f487809ed47ee#diff-37854d19817c792316d481f5beb93cc7) to the license limits translation work (no derivatives).

**Comment by freyjaodds** [comment]
Hei @arve0, I wanted to let you know that we are discussing this internally and we will get back to you within a few days. 

I had a call with Helge a while ago but I don't think we have talked - to introduce myself, my name is Freyja and I'm responsible for managing Code Club's international community. If you ever have any questions or concerns, do feel free to get in touch with me at freyja@codeclub.org.uk!

**Comment by freyjaodds** [comment]
Hi again @arve0. We have changed the licence so that it now doesn't mention "No derivatives" and shouldn't hinder any translation work. Many thanks for pointing this out!

https://github.com/CodeClub/python-curriculum/blob/master/LICENSE.md
