### ISSUE TITLE
WEB: <div> tag

### ISSUE THREAD

**Issue by ArgTang** [kodeklubben/oppgaver#281]
### Introdusere <div> tagen til slutt?

Siden div tagen er den mest generelle og en skal brukes hvis ikke innholdet passer inn i de andre taggene, skulle vi skrevet om til å introdusere denne til slutt?

som et eksempel: http://marksheet.io/ tutorialen liker jeg nettop fordi den gjør akkurat dette.

**Comment by larsfk** [comment]
Ja så du tenker å ha denne oppgaven som en senere oppgave istedet for såpass tidlig?

**Comment by ArgTang** [comment]
Introdusere header, footer, section osv først tenker jeg er bedre. Skal jeg se på det?

**Comment by larsfk** [comment]
Da skjønner jeg hva du mener, sikkert lurt det siden HTML5 er så bra som det er. Jeg tok bare utgangspunkt i måten jeg lærte det på jeg. Jeg skal se om jeg får sett på det i dag, så kommer det isåfall en ny Pull Request iløpet av dagen. Må bare bli ferdig med litt CSS-oppgaver først. :)

**Comment by larsfk** [comment]
Begynner å se på det i dag, men skal på ferie så det blir ferdigstilt i midten av august tenker jeg ;)

**Comment by tjesi** [comment]
@larsfk ble dette gjort? Det er ikke henvist til PR.
