### ISSUE TITLE
arduino-guiden.no eksisterer ikke lengre

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#284]
Noen som kjenner han som laget ressursen?

Lager en PR som fjerner ressursen, inntil den er oppe igjen. Ref #141

**Comment by tjesi** [comment]
En fra Kodeklubben Kristiansund som lagde den, men han har nå flyttet til Danmark og vi har ikke noe kontakt lengre.

**Comment by arve0** [comment]
Vi får reversere #285 hvis siden dukker opp igjen.
