### ISSUE TITLE
Oppgave ang samarbeid på Github

### ISSUE THREAD

**Issue by larsfk** [kodeklubben/oppgaver#288]
Jeg jobber med en oppgave ang publisering vha Github pages og har fått spørsmål og en ide servert ang å lage en oppgave på hvordan samarbeide på github. Vi vet jo alle at Git ikke er verdens letteste greie, så spørsmålet er om dette kanskje blir for komplisert i første omgang? 

Tanker?

**Comment by ArgTang** [comment]
Kan bruke GUI github appen er enkel og grei

https://www.youtube.com/watch?v=BKr8lbx3uFY

**Comment by larsfk** [comment]
GUI-appen er introdusert i den nye "HTML: Publiser din nettside", og der er det kun snakk om "Compare", "Commit" og "Push". Har også lenket til andre ressurser for de som vil lese mer, så usikker på om jeg skal bruke noe særlig tid på å lage en spesifikk GitHub-oppgave...

**Comment by ArgTang** [comment]
En oppgave med å jobbe flere stykker på samme github repo kunne hvert fint. Men det kommer ann på om det er behov, løses oppgavene mest individuelt er det nok ikke så viktig

**Comment by larsfk** [comment]
Kan se på det hvis jeg får tid, men det blir ikke prioritert

**Comment by teodorlu** [comment]
Jeg synes dette hadde vært nyttig. Etter Web-kurs i høst i fjor var det flere som hadde laget ting de ville publisere, og det kan gjøres kjekt med Git og github.io.

**Comment by tjesi** [comment]
Lukker denne pga inaktivitet. Har også beskrevet hvordan bruke Git på nye [wikien](https://github.com/kodeklubben/oppgaver/wiki/Komme-i-gang-med-Git).
