### ISSUE TITLE
Python: Hvor gammel er du?

### ISSUE THREAD

**Issue by DojeKM** [kodeklubben/oppgaver#300]
Beskriv ditt problem...Del 2: Variabler {.activity}

Hva: Variabler gjør at vi kan lagre tekst eller tall i datamaskinen. Tenk på det som en eske som vi putter tall eller bokstaver inni. Utenpå skriver vi hva som er inni esken. Dette er variabelnavnet.

Hvordan: For å lage en variabel skriver du navnet på variabelen som du velger selv, deretter = og det du ønsker å lagre i variabelen.

Eksempler: Prøv dem ut og se hva som skjer
tips: under dette
variabel = 4
petter = 'En gutt'
frida = 'En jente'
et_tall = 3
enda_et_tall = variabel + etTall (<-----)
tips: ovenfor dette
print(frida)
print(frida)
print(petter)
print(variabel - et_tall)
print(enda_et_tall)

finn en feil!

**Comment by arve0** [comment]
Takk for tilbakemeldingen 👍 Forstår jeg deg riktig, er det bare `etTall` som er feil?

**Comment by DojeKM** [comment]
ja

2016-09-19 21:43 GMT+02:00 Arve Seljebu <notifications@github.com>:
