### ISSUE TITLE
Scratch: King Kong

### ISSUE THREAD

**Issue by demring** [kodeklubben/oppgaver#302]
Flyet responderer ikke til kodene som beskrevet (de vises ikke på skjermen, i spillet, i det hele tatt, om man følger oppskriften).

**Comment by gahjelle** [comment]
Heisann,

takk for tilbakemeldingen. Såvidt jeg klarer å se virker det som om koden er riktig slik det står nederst i Steg 4. Har du de samme tallene der med minuser der de skal være? Og vis-klossen er lagt til?

Om du evt kan legge ut prosjektet ditt og gi meg en lenke kan jeg se om det er noe som mangler i koden eller om det er en feil i oppskriften.

**Comment by teodorlu** [comment]
Ser ut som vi ikke får noe svar, så jeg lukker denne. @demring - åpne igjen hvis det trengs.
