### ISSUE TITLE
Python: Hvor gammel er du?

### ISSUE THREAD

**Issue by Vgsjovik** [kodeklubben/oppgaver#310]
Problem er vel kanskje en overdrivelse...

Dette er en flott artikkel(?). 
Dere burde oppdatere årstallet til 2016. Og snart 2017.

-Vegard

**Comment by arve0** [comment]
Takk for tilbakemeldingen! Blir fikset i kveld om ingen kommet meg i forveien.

**Comment by gahjelle** [comment]
Dette er kanskje ikke stort nok til å legge mye arbeid i det, men det burde være mulig å alltid bruke inneværende år automatisk? En enkel løsning er vel å embedde javascript i md-fila, men vet ikke hvordan det vil samarbeide med pdfene? Alternativet er kanskje noen variabler som blir tolket av byggeren (da kan det ta noen dager inn i 2017 før teksten oppdateres). Eller bare huske å oppdatere :)

**Comment by arve0** [comment]
Burde ikke være noe problem å legge js i fila. Skal sjekke om det fungerer
med PDF.
