### ISSUE TITLE
Python: PGZ - Løpende strekmann

### ISSUE THREAD

**Issue by anettefm** [kodeklubben/oppgaver#313]
Skulle gjerne hatt en beskrivelse av installering av pydamezero. Da vi ikke finner en for python 3.5

**Comment by arve0** [comment]
Hei! Takk for tilbakemeldingen 😄

Det skulle vært en installasjonsmanual, ja. Her har du en på engelsk: https://pygame-zero.readthedocs.io/en/latest/installation.html

**Comment by steinoro** [comment]
#934
