### ISSUE TITLE
Scratch: Lærerveiledning - Labyrint

### ISSUE THREAD

**Issue by microwaven** [kodeklubben/oppgaver#319]
When froskekonge touches skatten, then we're supposed to add a "stopp alle" instruction. This seems to stop the scripts started with the green flag, but doesn't stop the player from moving the frog around with the keyboard keys. Is this a bug or a feature in Scratch or the game description?

**Comment by gahjelle** [comment]
This is a "feature" of Scratch... The `stopp alle`-block stops all currently running scripts, but it does not block new scripts from starting, which is essentially what happens with the `når ... trykkes`-blocks that are used to moved the player around.

One solution could be to also set a `game_running`-variable to false and test against this each time the player is moving. This is a bit advanced for this kind of introductory project, but could possibly be mentioned as an extension towards the end...

Another solution would be to use the usual (and better) `for alltid`-loop with `hvis ... trykket`-blocks. These would then be stopped by the `stopp alle`-block. The reason this is not done is two-fold, this was the first project I wrote and I didn't know better at the time. Also, I think these blocks are easier to understand than a loop and an if-test ... (so again coming back to this being an introductory project).

The ultimate solution is possibly me actually finishing the teacher note I've been planning to write forever ...

**Comment by steinoro** [comment]
Lagt inn tekst om dette i lærarrettleiingane: #914 og #936.
