### ISSUE TITLE
Ressurser

### ISSUE THREAD

**Issue by Zay2k** [kodeklubben/oppgaver#32]
Det er ingen mulighet for å laste ned bilde- og lydfilene som trengs for å gjøre oppgaven. Foreslår å lage en knapp for nedlastning.

**Comment by gahjelle** [comment]
Ah ... det er et par av Scratchoppgavene opprinnelig fra Code Club UK som bruker eksterne ressurser (ihvertfall Fyrverkeri og Tegneprogram), og disse lenkene har blitt borte i flyttingen til ny bygger.

Vi kan ganske lett legge til en lenke til disse ressursene i begynnelsen av oppgaveteksten.

Jeg vet ikke om det er behov for / lett å fikse dette som en mer generell feature. Hva tror dere, @arve0 @kwrl ?

**Comment by arve0** [comment]
Det er ganske enkelt å loope gjennom alle folders og lage zip av de. Litt av problemet med zip i git er at det er en relativ stor fil og hvert bygg vil trigge en ny zip på 1-10MB. Det tar ikke lang tid før vi går tom for lagringsplass (1GB er vel grensen på et github repo), og historikk i [kodeklubben.github.io](/kodeklubben/kodeklubben.github.io) må da fjernes.

Men fortvil ikke! Det finnes klientside-kode som gjør fremtiden :sunny: (lys): https://stuk.github.io/jszip/

**Comment by arve0** [comment]
Så ja, en generell løsning er fullt mulig (og kanskje triviell). Men for nå burde dette ordnes i teksten med en lenke: `last ned [denne bildefilen](bildefil.png) før du starter`.

**Comment by gahjelle** [comment]
Jeg kan oppdatere scratch-oppgavene i løpet av i dag eller morgen.

**Comment by arve0** [comment]
fixed in #44
