### ISSUE TITLE
Web: HTML: Forsvunnet katt

### ISSUE THREAD

**Issue by TrymNor** [kodeklubben/oppgaver#320]
Steg 3  Han Forvant fra hagen i går.     Skal det Ikke være Han Forsvant fra hagen i går?

**Comment by arve0** [comment]
Jo, det skal det nok. Takk for tilbakemeldingen 😄 

Om du ønsker, kan du fikse det selv her: https://github.com/kodeklubben/oppgaver/blob/master/src/web/forsvunnet_katt/forsvunnet_katt.md

Se videoen for hvordan du gjør det: https://www.youtube.com/watch?v=v9CS62-MED4&feature=youtu.be
