### ISSUE TITLE
Lister som ikke er "ting som skal gjøres"

### ISSUE THREAD

**Issue by teodorlu** [kodeklubben/oppgaver#330]
Hei!

Jeg har en kommentar til hvordan oppgavene skrives og ser ut etterpå.

# Typisk oppgave i dag

De fleste oppgavene er bygget opp med to typer hovedoverskrifter, .intro og
.activity. F.eks:

> # Hemmelig beskjed! {.intro}

> Denne oppgaven lar deg ...

> # Steg én: bygge A ... {.activity}

> Vi starter:

> - Gjør slik
> - Gjør sånn.

> # Steg to: bygge B ... {.activity}

# Begrensninger med slik oppgaver formateres i dag

Alle lister under en {.activity}-overskrift blir "Gjør dette, så dette". Jeg
savner å kunne bruke lister til å forklare hva ting er, uten at det ser ut som
det er noe barna skal *gjøre*.

Du får altså de små firkantede boksene foran hvert listeelement, boksene som ser
ut som de skal krysses av når de er "gjort".

# Eksempel på dagens begrensninger

Eksempel på når dagens bruk av {.activity} gir uønskede effekter:

I HTML kan vi ha ting inne i hverandre. Her lager vi en overskrift og en liste i
en div:

- `div`
    - `h1`: Ting jeg liker
    - `ol`
        - `li`: Hunder
        - `li`: Katter
        - `li`: Pizza

Dette ser slik ut i HTML:

```html
<div>
  <h1>Ting jeg liker</h1>
  <ol>
    <li>Hunder</li>
    <li>Katter</li>
    <li>Pizza</li>
  </ol>
</div>
```

# Behov

Jeg ønsker
- Å kunne lage lister uten at de framstår som oppgaver
- Og at oppgavene fremdeles ser ut som resten av oppgavene. Hovedoverskrifter uten {.activity} eller {.intro} synes jeg ser malplassert ut.

# Løsningsforslag?

- Gjøre om på CSS så kun `.check` gjør at listeelementer blir sjekklister?
- Bakoverkompatibilitet?
- Fortsette som jeg har gjort i dag og bruke {.protip} på h1.

**Comment by arve0** [comment]
Høres ikke dumt ut med en ekstra klasse. Eventuelt gi lik stil til alle overskrifter, slik at du ikke trenger noen spesiell klasse.

**Comment by teodorlu** [comment]
Anser dette som løst med #379 !
