### ISSUE TITLE
Python: Fargespill

### ISSUE THREAD

**Issue by DonnyCraft1** [kodeklubben/oppgaver#331]
Norsk:
Når tiden løper ut, kan du fortsatt prøve å gjette deg frem, selv om du ikke ser bokstavene, noen ganger gjetter jeg riktig. Da kan jeg få uendelig med poeng.

English:
When the time runs out, i can try to guess witch colour it is, even when it's not showed. When i keep pressing enter while guessing colours, i sometimes get the correct colour. In this way, i can get unlimited points, even when the time has expired.

Her er koden/Here is the code:

```python
#!/usr/bin/python

# -*- coding: UTF-8 -*-

import tkinter
from random import randint


colours_eng = ['Red', 'Blue', 'Green', 'Pink', 'Black',
               'Yellow', 'Orange', 'Purple', 'Brown']
colours = ['Rød', 'Blå', 'Grønn', 'Rosa', 'Svart',
           'Gul', 'Oransje', 'Lilla', 'Brun']
colour = 0

points = 0

time_left = 30


def start_game(event):
    if time_left == 30:
        countdown()
    next_color()


def next_color():
    global points
    global colour

    if time_left > 0:
        box.focus_set()

    if box.get().lower() == colours[colour].lower():
        points = points + 1

    box.delete(0, tkinter.END)

    colour = randint(0, len(colours)-1)
    text = randint(0, len(colours)-1)

    label.config(fg=str(colours_eng[colour]), text=str(colours[text]))
    points_label.config(text="Poeng: " + str(points))


def countdown():
    global time_left

    if time_left > 0:
        time_left = time_left - 1
        time_label.config(text="Tid igjen: " + str(time_left))
        time_label.after(1000, countdown)
    else:
        time_label.pack_forget()
        label.pack_forget()
        box.pack_forget()


root = tkinter.Tk()

root.title("Fargespill")
root.geometry("475x300")

instructions = tkinter.Label(root,
                             text="Skriv inn fargen PÅ ordet, ikke selve ordet!",
                             font=('Helvetica', 15))
instructions.pack()

points_label = tkinter.Label(root,
                             text="Trykk enter for å starte.",
                             font=('Helvetica', 30))
points_label.pack()

time_label = tkinter.Label(root,
                           text="Tid igjen: " + str(time_left),
                           font=('Helvetica', 30))
time_label.pack()

label = tkinter.Label(root, font=('Helvetica', 100))
label.pack()

box = tkinter.Entry(root)

root.bind('<Return>', start_game)
box.pack()
box.focus_set()

root.mainloop()
```

**Comment by arve0** [comment]
Klarer ikke umiddelbart se noen feil. Kanskje @sgranberg , som har laget oppgaven, kan hjelpe?

**Comment by gahjelle** [comment]
Hehe... dette er nok et _easter-egg_ i spillet :stuck_out_tongue: 

Koden her (og i oppgaven) bare gjemmer entry-boksen, men skrur ikke av noe funksjonalitet. Om du legger til linjen `root.unbind('<Return>')` etter `box.pack_forget()` nederst i definisjonen av `countdown()` vil enter-knappen slutte å virke og da blir det slutt på gratispoengene :smile: 

Siden `root.bind(...)` er det siste som gjøres burde kanskje teksten skrives om litt om det skal inkluderes i oppgaven. Jeg kan se på det etterhvert ... (eller @sgranberg ...?)

**Comment by tjesi** [comment]
@sgranberg og @gahjelle : tenker dere å gjøre noe her? lukker inntil videre
