### ISSUE TITLE
Scratch: Tegneprogram

### ISSUE THREAD

**Issue by larsfk** [kodeklubben/oppgaver#35]
Fix: 
- Bakgrunnen kan ikke åpnes i Scratch (feil filformat)
- Problemer med ferdig program. Bugs ved skifting av farge

**Comment by gahjelle** [comment]
Jeg ser bakgrunnen bare ligger som BMP-fil i zip-pakken, jeg kan fikse dette (konvertere til png) når jeg uansett retter opp #32 (forhåpentligvis i løpet av i morgen).

Angående fargeskiftebugs: Har du noen flere detaljer om feilen? Så kan jeg evt se på den også!

**Comment by larsfk** [comment]
Strålende! 
Ang fargeskiftebugs, så skal vi forske litt mer på det!

**Comment by gahjelle** [comment]
Kult! Om det evt ligger et prosjekt tilgjengelig som bugger så sleng bare med en lenke så kan jeg også se :)

**Comment by larsfk** [comment]
Får hanke det inn neste uke :)

**Comment by gahjelle** [comment]
Problemet med bakgrunn er fikset i #44

**Comment by arve0** [comment]
Lukker denne, ettersom vi mangler detaljer på "Problemer med ferdig program. Bugs ved skifting av farge".

Åpne igjen om feilen kan reproduseres, legg ved lenke til prosjektet som har problemer.
