### ISSUE TITLE
Web: JS: Grunnleggende JavaScript

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#353]
> var variabel = tall; // "variabel" vil nå ha samme verdi som tall, selv når tall endres

Dette stemmer ikke for tall i js, gjør det vel?

**Comment by arve0** [comment]
```
> a = 42
42
> b = a
42
> a = 84
84
> a == b
false
```

**Comment by arve0** [comment]
> Prøv å endre på tall2, hva skjer med tall3?
tall3 er jo satt til å være det samme som tall2 og derfor blir den endret når tall2 blir endret.

@larsfk Hva mener du her? `Number` er jo immutable i js.

**Comment by teodorlu** [comment]
Ser ut som @larsfk slettet kommentarene sine, så jeg lukker denne.

**Comment by arve0** [comment]
Dette er enda et problem som ikke er fikset, åpner.

**Comment by teodorlu** [comment]
Tenker du på kommentaren `// "variabel" vil nå ha samme verdi som tall, selv når tall endres`, bør denne fjernes?

**Comment by arve0** [comment]
Mine siteringer er fra oppgaven, og jeg mener de er uriktige. Ville gjerne ha @larsfk sin kommentar, eller noen andres, i tilfelle jeg har misforstått noe.

Altså, mener oppgaven variabler av tall er mutable?

**Comment by teodorlu** [comment]
Mulig annen tolkning av kommentaren: _tall er immutable_.

```javascript
> var tall = 9
undefined
> var variabel = tall
undefined
> variabel
9
> talll = 99
99
> variabel
9
```

Omskrivning av kommentaren: _Når vi endrer på tall, endrer vi ikke på variabel_.

**Comment by teodorlu** [comment]
> - Prøv å endre på tall2, hva skjer med tall3?
> tall3 er jo satt til å være det samme som tall2 og derfor blir den endret når tall2 blir endret.

@arve0 Enig med deg om denne, tall er ikke referanser, men verdier. Stemmer for å fjerne sitatet "- Prøv å endre ... når tall2 blir endret" og skrive om kommentaren til "Når vi endrer på tall, endrer vi ikke på variabel".

**Comment by larsfk** [comment]
Sorry for sent svar! 
Mener poenget her var å vise at når vi endrer et tall, så endrer vi ikke variablen. Ser at det er beskrevet på en krunglete måte. Kan hende det var noe annet jeg hadde tenkt, men bare fjern det som er helt på jorde ;)

**Comment by TorkelV** [comment]
https://github.com/kodeklubben/oppgaver/pull/643
