### ISSUE TITLE
Python: Skilpaddetekst

### ISSUE THREAD

**Issue by 09teeik** [kodeklubben/oppgaver#368]
jeg har fulgt koden og er nå ferdig men, når jeg starter koden kommer det "Invalid Syntax" og TEXT blir rødt vet ikke hva som er feil og jeg håpet dere kunne hjelpe meg, eller fikse problem?? 
![skjermbilde](https://cloud.githubusercontent.com/assets/26740191/24404157/66aa5ff0-13c0-11e7-8afe-eb73998bc9b2.PNG)

**Comment by arve0** [comment]
Hei!
Kan du lime inn hele koden din? Trur kanskje problemet kan være over bildet du har limt inn.

**Comment by 09teeik** [comment]
![skjermbilde2](https://cloud.githubusercontent.com/assets/26740191/24405269/85896674-13c4-11e7-95e0-a29e4d9e26b8.PNG)

**Comment by arve0** [comment]
Ser ut som du mangler `}` etter `",": blank`.

Altså, `MOVES` er en ordbok som har denne syntaksen:

```
MOVES = {
  "key": "value",
  "another": 123
}
```

**Comment by gahjelle** [comment]
Velkommen @09teeik  :smile: 

Som du har opplevd er det ikke hele tiden Python er så hjelpsom i feilmeldingene sine. En ting den ofte sliter med er om du mangler en form for parantes (som her) eller fnutt (anførselstegn). Da blir Python ofte helt forvirret, og klarer bare å si `invalid syntax`.

Et generelt tips om du opplever det samme igjen er å lete etter manglende paranteser eller fnutter litt over det området Python markerer med rødt.

Lykke til videre med kodingen!

**Comment by teodorlu** [comment]
Lukker denne, jeg :)
