### ISSUE TITLE
Overgangsoppgaver

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#37]
Lag oppgaver som viser forskjellene på scratch/python/etc. Hallvard har allerede gjort dette for Java/python: https://www.ntnu.no/wiki/display/tdt4100/Java+for+deg+som+kan+Python

**Comment by gahjelle** [comment]
<liten avsporing>
Dette vil nok evt være en Black Diamond-oppgave (kanskje til og med double black diamond), men det er mulig å dra dette mye lengre: Lag et (f.eks.) pythonprogram som kan kjøre scratchkode. Scratchprogrammer kan lastes ned i det som er essensielt en zippet json-fil. Ut fra disse kan man dra ut klossene og oversette dem til tilsvarende python-kode!
</liten avsporing>

Ellers: jeg liker den originale ideen godt!

**Comment by arve0** [comment]
Lukker denne, ser ikke ut som det kommer til å bli gjort.
