### ISSUE TITLE
Kode om AppInventor: Space Invaders til Markdown

### ISSUE THREAD

**Issue by gahjelle** [kodeklubben/oppgaver#378]
Til Booster Kids Bergen i mars ble AppInventor-oppgaven Space Invaders oversatt til norsk. Se vedlegg. Denne burde kodes om til Markdown og legges inn på appinventor sidene våre.

PS. Jeg har også lenke til en google-doc og grafikken. Si ifra om du ønsker jobben :)

[Space Invaders oppgave.pdf](https://github.com/kodeklubben/oppgaver/files/913544/Space.Invaders.oppgave.pdf)

**Comment by teodorlu** [comment]
Har konvertert til Markdown, fått ut bilder, etc.: https://github.com/kodeklubben/oppgaver/pull/553

**Comment by tjesi** [comment]
Publisert i #1118
