### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/oppgaver#380]
Hvordan man skriver oppgaver bør skrives om.
Det jeg kommer på som er viktig framover er:

1. 
YAML-headeren må innholde variabelen language, som kan være "lik" nb, nn, sv, da og en.

2.
YAML-headeren må inneholdevariabelen tags. Under tags ligger det som skal vises i filteret. Hvis oppgaven man skriver er på norsk bokmål kan det stå:
- tema: [mobil-apper, elektronikk, interaktive, blokkbasert, tekstbasert, minecraft, nettsider, spill, robot, animasjon]
- fag: [norsk, matematikk, engelsk]
- nivå: [barnehage, 1.-4. klasse, 5.-7. klasse, 8.-10. klasse, vgs]

Hvis oppgaven er på et annet språk, må alle underpunktene i tags være på det språket oppgaven er på. F.eks tags: topic: [games, minecraft] hvis language: en

3.
Man må lage nye eksempler i forhold til checkboxes som er en helt ny feature for oppgavene. En checkbox blir lagt til hvis det er nye linje og [ ]
Legg merke til at det er et mellomrom mellom klammetegnene

**Comment by NorwegianKiwi** [comment]
De forskjellige tag'ene bør være forhåndsdefinerte i kode, og de som ikke er definert bør bli ignorert. Enten så bør alle tags være på ett språk (norsk eller engelsk), eller så kan vi ha alternative navn på taggene i de forskjellige språkene.

**Comment by gahjelle** [comment]
Jeg ser ryddigheten i at tag'ene er forhåndsdefinerte, men jeg er litt skeptisk til at det blir tungvint å innføre nye tag'er hvis man er avhengig av å endre koden for å gjøre det.

Det er ikke et veldig renn av oppgaver slik at å sjekke at tag'ene er fornuftige faller greit inn under prosessen som allerede finnes i dag for "oppgave review". Og om noen innfører en ny tag eller feilstaver en eksisterende tag vil jo det bli ganske tydelig i filteret så ser ikke at det skjer ved uhell ...

**Comment by Skagevang** [comment]
Så tagging av oppgaver skjer på norsk uansett språk, men ikke lage en sjekk på om taggene er korrekte?

**Comment by Skagevang** [comment]
Ble vi enige her?

**Comment by Skagevang** [comment]
Jeg og Sondre har tenkt litt mer på tagging av oppgaver i forhold til oversettelse. Vi har kommet fram til at vi er enige med @NorwegianKiwi om at alle oppgaver bør "tagges" med tags: topic: [games, etc] og disse bør være forhåndsdefinerte og på engelsk. Oppgaven bør også bli ignorert hvis taggingen ikke passer. Dette vil bli klart best for framtiden med tanke på å implementere flere språk eller hvordan generelt filteret vil se ut.

**Comment by gahjelle** [comment]
Kan vi ta denne diskusjonen i plenum et sted?

Som nevnt er jeg litt skeptisk til om taggene skal være forhåndsdefinerte i byggeren. La meg prøve å forklare hva jeg tenker på med et use case. Om jeg har misforstått noe så oppklar gjerne:

Geir Arne Oppgaveskriver skriver en ny oppgave - la oss om Sonic Pi - som blir den første oppgaven som omhandler musikkprogrammering. Han ser over den forhåndsdefinerte listen over tagger, men finner ikke `musikk` (evt `music`). Han har da tre valg:

1. La være å bruke musikk som tag fordi han ikke vet hvordan han kan oppdatere listen over forhåndsdefinerte tagger, eller fordi det virker som for mye arbeid å gjøre det.
2. Bruke musikk som tag selv om den ikke virker.
3. Oppdatere den forhåndsdefinerte listen av tagger ved å lage en PR mot oppgavebygger-koden.

Jeg vet ikke om det er alternativ 3 man ser for seg at oppgaveskrivere skal gjøre? Om så vil jeg si at jeg tror det veldig raskt degenererer til alternativ 1.

Dersom vi istedet tillater tagger vil scenariet heller være "Geir Arne Oppgaveskriver skriver sin Sonic Pi-oppgave. Han ser at taggen musikk ikke er brukt tidligere, men ser også at hans nye oppgave dekker et nytt område. Han legger derfor på den nye taggen musikk. Ting virker."

Den eneste mulige bakdelen med dette som jeg ser er at det gir oppgaveskrivere muligheten til å lage et villniss av tagger, evt med forskjellige stavemåter av samme tagg. Men dette har vi allerede rutiner som hindrer:

1. Det skrives ikke veldig mange nye oppgaver. Det gjøres "code review" på alle nye oppgaver. Å sjekke at taggene gir mening er veldig lite ekstra arbeid (vi bør uansett ha en liste over _anbefalte_ tagger).
2. Når taggene vises på den nye siden blir det veldig tydelig om man har en skriveleif (f.eks `Windows (238) Windosw (1)`)

Hvilke andre fordeler har det å forhåndsdefinere tagger som gjør at dette blir klart best for fremtiden?

**Comment by Skagevang** [comment]
Det viktigste problemet du glemmer her er at den nye siden allerede har fått implementert støtte for forskjellige språk. Så hvis man skal introdusere nye tagger, må dette endres i codeclub-viewer repoet uansett. Hvis ikke kommer filteret til å vise engelsk tags på norsk f.eks. (Hvis alle oppgavene er tagget på engelsk)

**Comment by Skagevang** [comment]
Skjønner at det er litt vanskelig å se for seg alt nå, siden ikke alt er merget eller bygget til betasiden

**Comment by gahjelle** [comment]
Men kommer ikke taggene fra de oppgavene som er merket med det språket man har valgt? Altså om jeg ser norske oppgaver er ikke taggene hentet fra de norske oppgavene?

Når du sier at man må endre codeclub-viewer er det fordi dere har oversettelser av tagger fra engelsk til norsk kodet inn i koden? Igjen sliter jeg med å se hvilke fordeler dette har kontra å gjøre det mulig for oppgaveskrivere å endre på tagger.

**Comment by Skagevang** [comment]
Hvis man forhåndsdefinerer og tagging av oppgaver skjer på engelsk, vil dette skje: Man velger f.eks. engelsk språk på forsiden. Filteret endrer språk til engelsk og man viser bare de engelske oppgavene. Men man kan trykke på norsk i filteret i tillegg. Da plusser man bare de norske oppgavene med de engelske og man får flere oppgaver i filteret, men ikke flere tags. Bytter man da språk til norsk igjen byttes bare språket i filteret

Alt av oversetting ligger i codeclub-viewer allerede nå i egne filer for hvert språk.

**Comment by gahjelle** [comment]
OK, ser at det krever forhåndsdefinerte tagger. Takk for info.

Neste forespørsel :) Kan disse oversettingsfilene utvides av filer som ligger i oppgave-repoet? Egentlig tilbake til mine tidligere tanker. Oppgaveskriverene burde ikke trenge å forholde seg til oppgavebyggeren. Om man må oppdatere en liste over tagger burde det kunne gjøres i oppgave-repoet.

Dette vil også skalere bedre om man ser for seg at codeclub-viewer i fremtiden plutselig gjør andre ting enn å vise kodeklubb-oppgaver vil listen over relevante tagger kunne være ganske forskjellig for hvert "oppgave"-repo. Det vil da være en fordel å kunne endre denne på oppgave-repo-nivå, i stedet for at taggene i codeclub-viewer skal inkludere alt.

**Comment by Skagevang** [comment]
Jeg tror nesten @NorwegianKiwi må svare på dette, da jeg ikke har hatt så mye med språk generelt å gjøre, men heller filteret og localStorage

**Comment by NorwegianKiwi** [comment]
Jeg tror kanskje @gahjelle sitt forslag om å definere tags i forskjellige språk i oppgaverepoet er en god løsning. Synes vi skal utforske dette videre.

I grunn bør alt som er direkte relatert til oppgavene være i oppgave-repoet, men alt som er "generelt" være i codeclub-viewer. Regner med det blir noen gråsoner, og da får vi diskutere.

**Comment by Skagevang** [comment]
Se #411
