### ISSUE TITLE
Oppgave-telleren i beta er feil

### ISSUE THREAD

**Issue by larsfk** [kodeklubben/oppgaver#383]
Oppgave-telleren på forsiden i beta-en er feil. I Scratch står det 97 oppgaver og det er langt mindre.

**Comment by gahjelle** [comment]
Jeg vil gjette på at den også teller oppgaver i oppgavelister? Det er en del oppgaver i lister som ikke er enkeltstående oppgaver, for eksempel i Interaktive Oppgaver. Men noen oppgaver blir kanskje også telt dobbelt?

**Comment by Skagevang** [comment]
Det blir fikset i [https://github.com/kodeklubben/codeclub-viewer/pull/279](#279 codeclub-viewer)

**Comment by arve0** [comment]
Denne gjelder codeclub-viewer, og er ikke relatert til hvordan oppgavene er skrevet eller strukturert, så lukker her.
