### ISSUE TITLE
Oversette kursinfo

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/oppgaver#409]
Det ligger nå en PR på at kursinfomasjonen støtter språk. navnet til index-filen i kursmappa må være på denne strukturen: index_no.md eller index_en.md

**Comment by arve0** [comment]
Kan du peke til PR? Er litt utydelig for meg hva dette innebærer. For eksempel, gjelder dette også root index?

**Comment by Skagevang** [comment]
https://github.com/kodeklubben/codeclub-viewer/pull/284

**Comment by krskog** [comment]
Dette gjelder **bare** `/course/index` filer!
Slik det er satt opp nå trenger man ikke endre noe ved eksisterende `index.md`. De vil fungere som indexen til Norsk Bokmål og være "hoved-indexen" som blir hentet ut om det ikke finnes indexer i andre språk. Indexer i andre språk må da ha navn `index_(ISO_CODE).md`, for eksempel `index_sv.md`.

**Comment by Skagevang** [comment]
Se #465
