### ISSUE TITLE
Oppdatere README.md

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/oppgaver#411]
`/README.md` som beskriver hvordan vi kommer i gang med oppgaveskriving er utdatert. Det som må legges til er:

- Oppgavene skal være tagget med: `language: nb` hvis det er norsk. Oppgaver på andre språk kan bruke nn, sv, da og en. 
- Oppgavene skal også tagges med tanke på filteret. Se #410 !
- Hvis man vil ha checkboxes i oppgavene må man bruke syntaksen `- [ ]`

**Comment by arve0** [comment]
> Oppgavene skal være **tagget** med: language: nb hvis det er norsk. (min uthevning)

Regnes språk som en tag på de nye sidene?

**Merk**: I dag er formatet ikke beskrevet *fullt* i README.md, men i [FORMAT.md på codeclub_lesson_builder](https://github.com/arve0/codeclub_lesson_builder/blob/master/FORMAT.md). README.md inneholder en lenke dit. I tillegg inneholder [src/scratch/README.md](https://github.com/kodeklubben/oppgaver/blob/master/src/scratch/README.md) formateringsinformasjon som spesifikk gjelder scratch-oppgaver.

**Comment by Skagevang** [comment]
Skjønner ikke helt hva du spør om? Oppgaven må tagges med language i YAML-headeren så man kan filtrere etter språk

**Comment by arve0** [comment]
Var bare et spørsmål om terminologi, ingen fare 😄 Når du sier tag, tenker jeg merkelapp, eller

```yaml
---
tag: 
  - dette er en merkelapp
  - en annen merkelapp
---
```

Altså noe annet enn egenskaper (properties):

```yaml
---
title: Tittel er en egenskap til oppgaven
language: Språk er en annan property
---
```

**Comment by Skagevang** [comment]
Språk er da altså en merkelapp ;) Men har egentlig kurs blitt tagget feil tidligere da? Nå er det sånn her
`---
tags:
  tema: [animasjon, spill]
---`
Men oppgavene bør tagges slik?
`---
tags:
  topic:
    - animation
    - game
---`

**Comment by arve0** [comment]
Kommer ann på om du det er mange tags. `liste: [item1, item2]` er enlinjersversjonen av

```
liste:
  - item1
  - item2
```

Altså, de er ekvivalente.

Oppdaterte kommentaren din (bruk tre ` backticks med kode over flere linjer).

**Comment by teodorlu** [comment]
Hei!

Jeg skjønner ikke hva som er ugjort på denne saken. Kan vi spesifisere i OP?

- Skal README.md i alle oppgavemapper være tagget med språk etter språk oppgaven i samme mappe er skrevet på?
- Er vi enige om format for tagging?
- Gjelder det [alle disse filene](https://pastebin.com/NM5v11Vn)?

Skal det bli gjort noe er det fint med spesifikke oppgavespesifikasjoner :)

**Comment by Skagevang** [comment]
Dette issuet gjelder selve readme-en til oppgave-repoet. Så kun oppdatere den til at det er lett for nye oppgaveskrivere å starte å skrive oppgaver. Her mangler det info om å legge til språk og tags i YAML, noe som må gjøres før en oppgave blir godkjent. Og syntaxen for å lage checkboxes, noe som også er veldig kjekt siden man kan se progresjonen nå.

**Comment by teodorlu** [comment]
OK. Jeg la til en linje i din OP øverst her -- endre om du er uenig!

**Comment by steinoro** [comment]
Dette arbeidet er godt i gang med wikien @Oisov og eg har laga på https://github.com/Oisov/oppgave/wiki.

**Comment by tjesi** [comment]
Løst.
