### ISSUE TITLE
programmering.wiki.ifi.uio.no er nede

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#413]
Vi lenker til http://programmering.wiki.ifi.uio.no/Linux-oppgaver i den eksterne oppgaven [src/kommandolinje/norskintro/norskintro.md](https://github.com/kodeklubben/oppgaver/blob/master/src/kommandolinje/norskintro/norskintro.md).

Jeg har ikke klart å finne ut hvem som administrerer wiki.ifi.uio.no.

**Comment by teodorlu** [comment]
Siden ser ut til å være oppe nå. To muligheter:

1. Beholde ting som det er og la UIO ta seg av oppetid
2. Legge til ekstra link til [arkivert side](http://archive.is/0REQv)

**Comment by arve0** [comment]
Ettersom nedetiden ikke er permanent, anser jeg denne som løst.
