### ISSUE TITLE
Legg inn introduksjon i eksterne oppgaver

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/oppgaver#449]
Det er lagt inn en PR i codeclub-viewer [(trykk her for å se)](https://github.com/kodeklubben/codeclub-viewer/pull/297) som henter ut introduksjonen og bildet i oppgaven når man holder musa over oppgaven på kurssiden. Dette fungerer ikke på noen av de eksterne oppgavene, fordi det er bare merkelapper i YAML-headeren for de oppgavene. Forslaget mitt er å legge inne en liten tekst og et bilde (kan være gif, hvis man vil vise animasjon) i alle oppgavene som er eksterne også. f.eks 
![image](https://user-images.githubusercontent.com/11090538/27862623-6e6df42c-6186-11e7-8d66-bc503e1b8cf8.png)

**Comment by tjesi** [comment]
Denne ble løst for lenge siden...

**Comment by Skagevang** [comment]
Denne er ikke løst. Se engelske microbit-oppgaver f.eks.

**Comment by tjesi** [comment]
Løst.
