### ISSUE TITLE
Bedre README-filer for Scratchoppgaver

### ISSUE THREAD

**Issue by gahjelle** [kodeklubben/oppgaver#45]
README-filene i oppgavekatalogene kan brukes for å gi info om oppgavene til veiledere og lærere. For Scratchoppgavene er flere av disse utdaterte, inkonsistente og trenger litt kjærlighet :)

**Comment by arve0** [comment]
Kanskje beskrivelsen av scratchblocks i README.md i roten burde flyttes over?

Disse to burde også legges til:
http://blob8108.github.io/scratchblocks2/
http://blob8108.github.io/scratchblocks2/generator/

**Comment by gahjelle** [comment]
Ja, det er sikkert ryddigere å ha de språkspesifikke tingene et nivå inn. Jeg fikser :)

**Comment by gahjelle** [comment]
Da har endelig dette arbeidet så smått begynt :) #184 #186

**Comment by arve0** [comment]
Flere av lærerveiledningene er nå tilgjengelig.
