### ISSUE TITLE
Automatisk bygg og publisering

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#46]
https://developer.github.com/webhooks/

**Comment by gahjelle** [comment]
Ser ut som om det er veien å gå :+1:

**Comment by arve0** [comment]
Vi med det samme kan vi implementere Travis CI, slik at vi vet at siste bygg er OK:

**epost**
![skjermbilde 2015-02-20 kl 15 05 00](https://cloud.githubusercontent.com/assets/4810521/6287478/266c967a-b912-11e4-9edd-ee8feb6d21c3.png)

**på travis kontrollpanel**
![skjermbilde 2015-02-20 kl 15 04 43](https://cloud.githubusercontent.com/assets/4810521/6287485/36b9f338-b912-11e4-8994-584001ab1bbb.png)
![skjermbilde 2015-02-20 kl 15 04 05](https://cloud.githubusercontent.com/assets/4810521/6287487/388c3810-b912-11e4-8841-5044a2ad9244.png)

**Comment by gahjelle** [comment]
Bedre og bedre! :D 

Ser også at vi burde rydde litt i weboppgavene :)

**Comment by arve0** [comment]
Ja, forslår vi fjerne web-katalogen fra bygg inntil #21 er ferdig. Så kan vi heller lage en web-branch som peker til bygger med web inkludert i config.js.

**Comment by gahjelle** [comment]
Høres bra ut! Kjør på! :)

**Comment by arve0** [comment]
[jenkins](http://jenkins-ci.org) er nok enklere enn å lage sin egen webhook.

**Comment by arve0** [comment]
@kwrl setter i gang automatisk bygg i løpet av helgen.
