### ISSUE TITLE
Oppgave: Python + rPi + Minecraft = sant?

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#50]
http://www.raspberrypi.org/learning/getting-started-with-minecraft-pi/

**Comment by arve0** [comment]
https://github.com/fogleman/Minecraft

**Comment by arve0** [comment]
https://github.com/brooksc/mcpipy/
https://mcpipy.wordpress.com

**Comment by Helgenen** [comment]
Oioi, den var flott! Den har jeg lyst til å prøve:)

Fri Feb 20 2015 at 23.22.05 skrev Arve Seljebu <notifications@github.com>:

**Comment by arve0** [comment]
Men ser ut som det er dårlig støtte for de som ikke har rPi. Dumt for de
klubbene som rPi-oppsett er tungvindt. Hold oss oppdatert med det du finner
ut! :-)

**Comment by Helgenen** [comment]
Folkeverkstedet på Deichman i Oslo har kjøpt 15 rPi's, så der kan man gjøre
noe. Men ja, en tilsvarende for vanlig Minecraft hadde vært fett. Trur
dette kan gjøres omtrent likt i Computercraft da...

Mon Feb 23 2015 at 08.58.54 skrev Arve Seljebu <notifications@github.com>:

**Comment by jmbjorndalen** [comment]
En liten disclaimer: jeg har ikke brukt Raspberry-versjonen, så jeg har ikke full oversikt over hva den støtter. Det kan se ut som den bare støtter en veldig begrenset Minecraft-api, men nok til at man kan se hvor en spiller er og gjøre noen enkle ting med blokker: 
     http://www.stuffaboutcode.com/p/minecraft-api-reference.html
Han som la ut referansen har også lagt ut informasjon av en Canarymod-plugin han vedlikeholder som skal støtte Raspberry-koden på en PC-versjon av Minecraft: 
     http://www.stuffaboutcode.com/2014/10/minecraft-raspberryjuice-and-canarymod.html

En veldig kjapp kikk på implementasjonen bekrefter mistanken: 
https://github.com/martinohanlon/CanaryRaspberryJuice

de bruker en enkel protokoll over en socket for å sende og motta kommandoer og data. Det gjør det enkelt å koble opp Python (og egentlig hvilket som helst språk), og det er lett å starte og stoppe Python-programmet uten å måtte stoppe Minecraft-serveren. Ulempen er at det kan bli mer komplisert å støtte callbacks (som Minecraft-API'ene bruker _mye_), og det er begrenset hvor mye man får tilgang til av f.eks. Canarymod-API'en. 

Samtidig: hvis man bare trenger å støtte øvingsopplegget fra Raspberry-Pi-versjonen ser det ikke ut som det burde være så vanskelig å få til på en PC.

**Comment by jmbjorndalen** [comment]
*ComputerCraft* (kjapp intro for de som ikke kjenner den) : her kan man lage egne blokker som kan settes sammen til datamaskiner med skjermer. Det finnes egne programmerbare roboter ("turles") som man kan programmere til å bevege seg rundt og gjøre forskjellige ting.

http://www.computercraft.info/

Programmeringsspråket her er Lua. Det er et ganske enkelt og lite språk som relativt enkelt kan bygges inn i programmer hvis man trenger mulighet for scripting. Jeg vet det skal være brukt i en del spill (uten at jeg har oversikt), så det kan hende unger som lærer seg Lua kan dra nytte av det i andre spill. 

Jeg har lekt meg litt med ComputerCraft, og man kan gjøre mye gøy der. Det er derimot _ikke_ egnet for å lage "mods" eller scripte selve minecraft. I ComputerCraft har man bare en begrenset tilgang til omgivelsen rundt datamaskinen eller roboten, så man kan hakke, knuse og plassere blokker, lese av og sende redstonesignaler og annet, men man kan ikke komme under huden på Minecraft for å endre på ting. Ønsker man å "modde" flaggermus slik at de bæsjer lava (jeg har en privat liten idé om hvorfor man finner lava på de merkeligste steder i Minecraft, men det kan vi utdype ved annet høve) er ikke ComputerCraft løsningen. 

ComputerCraft trenger Forge, så må man selvfølgelig installere det. Det enkleste er kanskje å bruke Feed The Beast eller ATLauncher for å starte opp Minecraft. Velger man en "modpack" som har ComputerCraft installert slipper man å sette opp ting selv.

**Comment by jmbjorndalen** [comment]
*ScriptCraft* (http://scriptcraftjs.org/) er en av favorittene mine for å scripte i Minecraft for tiden. Den var opprinnelig lagd for Bukkit, men Walter Higgins jobber med en port til CanaryMod nå som Bukkit er død. Jeg har ikke fått sett så mye på den siden jul, men det virker som han har fått det meste og viktigste på plass. 

Walter Higgins har lagd en guide for å komme i gang med ScriptCraft som også viser hvordan man setter det opp og hvordan man bruker enkle (og noen litt mer avanserte) programmeringskonsepter for å scripte bygging og annet i Minecraft. 

https://github.com/walterhiggins/ScriptCraft/blob/master/docs/YoungPersonsGuideToProgrammingMinecraft.md

Noen av fordelene med denne er: 
- man kan gjøre mye rart her som ikke ser ut til å være støttet i raspberry-versjonen
- den er relativt enkel å komme i gang med
- vil man dykke dypere har man direkte tilgang til CanaryMod-API'en gjennom JavaScript-bindingene. Da kan man gjøre det meste av det som er mulig fra Java-API'en. Det er noen begrensninger i mapping mellom Java og JavaScript, og det var vanskelig å få til å lage nye blokktyper i Bukkit (jeg er usikker på om det er enklere i CanaryMod), men ellers kan man gjøre veldig mye artig modding direkte fra JavaScript. 
- man kan skrive enkle kommandoer på tekstlinjen i Minecraft og nå ting man har lag derifra. 
- man kan også koble seg på event-systemet i Minecraft slik at man kan hekte seg på ting som skjer i spillet. Sånn sett burde det ikke være så vanskelig å få creepere til å sprute blomster istedet for å sprenge blokker. 
- det er mye enklere å komme i gang enn hvis man skal sette opp en utviklingsomgivelse for å gjøre MineCraft-ting i Java. 
- det går an å bruke ScriptCraft som en slags overgang til Java-APIen hvis noen vil den veien. 
- kompliserte script kan redigeres i en enkel tekst-editor. Man trenger ikke en full IDE eller Java-utviklingsomgivelse. 
- det følger med en del eksempler. 

Ulemper: 
- ikke Forge-støtte for de som ønsker det. 
- JavaScript (for de som ikke liker det)
- den kjører i Minecraft-serveren, så man må se der etter feilmeldinger. Heldigvis er det veldig lett å kjøre "reload" på scriptene man skriver, så man trenger ikke starte serveren på nytt hvis man skal prøve noe nytt. 

Den er i hvert fall verd å ta en kikk på. I hvert fall for unger som kanskje ville synes Raspberry-Pi-programmeringen ble for kjedelig og begrenset.

**Comment by jmbjorndalen** [comment]
Ellers var det noen løsninger for å lage plugins i Bukkit ved hjelp av Python. Det er en stund siden jeg sjekket, men det virket som de døde litt ut. Felles for dem var at de lastet inn Jython (en Java-implementasjon av Python). Dermed hadde man direkte tilgang til Java-API'en fra Python, og man kunne også lage Python-klasser som kunne brukes _fra_ Java-koden. 

http://dev.bukkit.org/bukkit-plugins/python-plugin-loader/
http://dev.bukkit.org/bukkit-plugins/pploader/

Limet for å få lastet opp Jython og få sparket i gang Python-modulene var ikke så forferdelig stort, så det burde være mulig å få noe lignende til for CanaryMod og lignende. 

I prinsippet burde det også være mulig for Forge, men litt avhengig av hva man ønsker å gjøre kan det bli litt mer komplisert med dynamisk lastbare moduler der siden Forge-mods typisk endrer både på klient og server. Dermed trenger man kanskje å koordinere script reload på server og klientene som er tilkoblet.

**Comment by arve0** [comment]
http://blog.macuyiko.com/post/2015/rebuilding-our-jython-console-plugin-for-minecraft.html

@jmbjorndalen du har sett computercraftoppgavene @gahjelle har laget?

**Comment by arve0** [comment]
https://github.com/Macuyiko/MinecraftPythonConsole/blob/master/README.md

**Comment by arve0** [comment]
@kwrl @larsfk

**Comment by jmbjorndalen** [comment]
Hei @arve0. Tror jeg har sett litt på noen av computercraft-prosjektene dem på et eller annet tidspunkt. Det virket i hvert fall kjent når jeg så på dem i full fart :-)  
Artig Python console. Den må vi kanskje få tatt en titt på @fjukstad og @olemb?

**Comment by arve0** [comment]
Spennende ide, men vi mangler noen som kan ta opp tråden.
