### ISSUE TITLE
Legge til i Travis: Bygg også mot codeclub-viewer

### ISSUE THREAD

**Issue by NorwegianKiwi** [kodeklubben/oppgaver#500]
For å sjekke at de endringene man gjør i oppgaverepoet ikke skal ødelegge for codeclub-viewer (den nye implementasjonen av sidene), så bør travis bygge både mot gammel bygger (codeclub_lesson_builder) og ny bygger (codeclub-viewer) før det er lov å merge.

**Comment by Skagevang** [comment]
Denne kan man vel close?
