### ISSUE TITLE
Stilguide for oppgaveskriving

### ISSUE THREAD

**Issue by teodorlu** [kodeklubben/oppgaver#566]
Jeg savner en stilguide til formatering av oppgaver. Vi har litt variasjon i hvordan vi formaterer ting, og jeg ønsker én standard. Da unngår vi å formatere ting fram og tilbake når vi redigerer, og kan sette opp editorer til følge guiden.

Dette blir mer aktuelt når vi skal ha review på alle endringer. Noen spørsmål:

1. Skal vi bruke `-` eller `+` til listeelementer?
    - Jeg har brukt `-` så langt, opplever dette som vanlig
2. Skal vi bryte linjene våre på 80 tegn eller la editor bryte linjer?
    - Jeg foretrekker harde `\n` før tegn 80 i avsnitt. Da er det lett å gjøre diff linje-for-linje. Når vi gjør endringer på et avsnitt får vi se akkurat hvor endringen er, uten å måtte kjøre diff ord-for-ord.
    - Dette krever at man endrer oppsettet i flere editorer (Sublime, Atom, VS Code)
    - Dette er også uvandt for de som er vant til å skrive i Word
3. Hvilke tags (`{.activity}`, `{.check}`) skal være på hvilke overskriftsnivåer (`#`, `##`)?
    - Global README gir hvordan ting skal gjøres.
    - ... men bør være i stillguide.
4. Konvensjon for Git-bruk?
    - Norsk/engelsk? Søk er lettere med ett språk
    - Commit-beskjeder: Begynne imperativ verb? `Legg til Python-oppgave om kryptografi`? Gjør ofte at det kommer tydeligere fram. Sammendrag som `computercraft` eller `ny oppgave` beskriver lite.
    - Navn på PR? `feature-45-elm-game`? `elm-add-game`? `fix-elm-game-bug`?
5. Bør vi se etter et verktøy for å autoformatere Markdown-filer etter stilguiden?
    - `elm-format` fyller liknende rolle for Elm. Jeg har brukt det litt, og er fornøyd. Standarden i Elm er å automatisk kjøre `elm-format` når du lagrer.
    - Jeg prøvde å sette opp Pandoc til å fylle liknende rolle (#567, ved å konvertere Markdown til Markdown). Dette syntes ikke å være en god løsning; jeg fikk problemer med tabeller og YAML-headeren. Vi trenger altså ikke en linter som forstår all strukturen, men kan reformatere hva den forstår.

Synes ikke vi trenger å være [superstrenge](https://github.com/torvalds/linux/pull/17#issuecomment-5659933) på at alle skal følge guiden, men er OK å (a) _ha_ en anbefalt stil; (b) ha en guide vi kan standardisere eksisterende innhold _mot_ og (c) kunne lenke til stilguiden når vi gjør slike endringer så det ikke er "jeg synes dette er pent og jeg har rett". Jeg tror vi tjener mye på at det skal være lett å komme i gang.

### Spørsmål

- Mener dere vi bør ha en stilguide?
- Kommentarer til punktene over?

Personlig har jeg lite erfaring med profesjonell systemutvikling i team. Kanskje @NorwegianKiwi har noe å komme med?

**Comment by teodorlu** [comment]
For å bryte avsnitt ved 80 tegn i forskjellige editorer:

- [Atom-pakke](https://github.com/atom/autoflow)
- Bruk `M-q` i Emacs
- Bruk `gqq` i Vim

**Comment by teodorlu** [comment]
Ser dette er (implisitt) hva vi har begynt med i #560 (Veiledning for hvordan å skrive veiledninger). Naturlig å legge en _Veiledning for hvordan å skrive oppgaver_ i samme mappe med link til en `mal_oppgave.md.txt`?

**Comment by tjesi** [comment]
Enig, vi bør ha en stilguide. Pr nå får man en del tips i README.md i [oppgave-repoet](https://github.com/kodeklubben/oppgaver/), samt at man kan se hvordan de andre oppgavene er skrevet. Men det er allikevel ikke alltid like lett å vite hva man skal gjøre, og eg ser stor verdi av å ha en mer klar guide og detaljert mal for de som skal skrive oppgaver.  Dersom vi i tillegg blir enige om en guide og formaterer alle eksisterende oppgaver etter dette, så blir det også lettere å følge dagens oppgaver som eksempel. Ref #567.

1. Før brukte vi `+`, men vi har egentlig blitt enige om å bruke `- [ ]` fremover. Det er ikke alle oppgaver hvor dette er fikset helt opp enda, og noen blander de to. Burde ta en gjennomgang og fikse det.
2. Støtter harde `\n` ved 80 tegn. Eg har ikke vert så flink til dette selv, men innser at det gjør ting mer lesbart.
3. Vi har vel forsåvidt en enighet om hvordan det skal gjøres, som kan sees i readme og oppgavene, men burde tydeliggjøres bedre.

Enig i at vi burde ha en veiledning for hvordan skrive oppgaver i samme mappe som malen for å skrive lærerveiledninger.

**Comment by teodorlu** [comment]
@arve0, @gahjelle: Hva mener dere? "Bare lag et forslag, så kan vi ta det derfra?"

**Comment by arve0** [comment]
Er positiv til en mal / guide. Viktig det ikke blir for omstendig, spesielt for nye bidragsytere. En kan for eksempel si noe slik som:

`Vi har en [mal](lenke_til_mal.html) og en [stilguide](lenke_til_guide.html) som du kan følge. Om det er vanskelig å få med seg alle detaljene, skriv gjerne oppgaven og send pull-request, så hjelper vi til med formateringen.`

**Comment by tjesi** [comment]
Når eg ble ny bidragsyter så savnet eg en god guide. Det står som nevnt en del ting i README.md i oppgave-repoet som er nyttig, men det er ikke strukturert på måten vi skriver oppgaver, og eg brukte en del tid på å se over andre (tilfeldige) oppgaver og lære av de, samtidig som eg fikk en del feedback via å sende inn PR. 

For å gjøre det enklere så burde vi ha en fil som har strukturen til en oppgave med ferdig header og overskrifter og punktlister osv, som forklarer hvordan ting bør være. Vi burde også velge et par oppgaver som vi synes er bra skrevet (feks. en i Scratch og en i Python for å vise både blokker og tekst) og som følger guiden, som vi kan lenke til som konkrete eksempler på gode oppgaver å lære av.

**Comment by arve0** [comment]
Ellers har jeg ikke noen preferanser for hvordan lister, overskrifter, etc, skal formateres. Men kjekt med en "fikser"/linter. Trur ikke pandoc md -> md er veien å gå, heller en enkel logikk som går direkte på teksten. Noe slik som:

1. test for et spesifikk mønster (for eksempel linjelengde > 80, # overskrift uten to \n\n)
2. hvis mønster passer, kjør transform

Så kan man begynne med de vanligste feilene, spesielt de som er knot å redigere manuelt.

**Comment by teodorlu** [comment]
Enig om Pandoc, ref #567 .

Tror du det er noe vi må skrive selv? Et kort søk ga en [pakke til Atom](https://atom.io/packages/markdown-format) som gjør noe liknende hva vi vil ha.

**Comment by arve0** [comment]
Tror noe som kjører i node er optimalt, slik at alle editorer vil fungere like fint. For eksempel https://github.com/DavidAnson/markdownlint

**Comment by teodorlu** [comment]
Enig, fint om det kan kjøre i Node.

Såvidt jeg forsto ga markdownlint en liste av feil, men kan ikke skrive om tekstfilene til å stemme med hvordan vi vil ha ting. Kan se ut som dette er mulig med [Remark.js](https://github.com/wooorm/remark).

**Comment by teodorlu** [comment]
Etter å ha fått litt avstand til denne saken er jeg mer skeptisk. Jeg reagerte på en overflod av innstrømmende oppgaver fra svært mange nye oppgaveforfattere, og følte meg en tid som en manuell linter -- en rolle systemutvikleren i meg mente burde automatiseres bort.

@arve0 har rørt ved inngangsterskelen for oppgaveskriving. Denne må være lav; det er alfa omega. Det kan være verdifult med en stilguide, men det ikke sikkert det er økonomisk om man kan legge den samme innsatsen et annet sted.

Lukker derfor denne saken, og foreslår at vi merger inn hva som ligger på `conventions`-branchen.
