### ISSUE TITLE
Skript for vurdering i lærarrettleiingane

### ISSUE THREAD

**Issue by steinoro** [kodeklubben/oppgaver#567]
Sidan det er bestemt at teksten om vurderingskriterier skal bli ein standardtekst burde det bli skrive eit skript som endrar dette.

Altså: endre teksten mellom `## Forslag til vurderingskriterier {.challenge}` og `## Forutsetninger og utstyr {.challenge}` til
"Det er mange ulike måter en kan vurdere et programmeringsprosjekt, og her må en selv vurdere hva som er den beste måten ut ifra hvilket fag man jobber i, hvilken aldergruppe og hvilket nivå elevene er på, hva man ønsker å teste og hvor mye tid man har til rådighet til å jobbe med prosjektet. I vårt [lærerdokument](../../pages/hvordan_bruke_lærerveiledning.html) har vi blant annet beskrevet ulike måter dette kan gjøres på, tillegg til en del andre nyttige tips til hvordan man underviser i programmering."

**Comment by teodorlu** [comment]
Kan du gi et konkret eksempel?

- Hvilken nåværende fil er feil
- Hva står der nå
- Hva vil du endre til

Bør ikke være så vanskelig med `find` og `sed`.

**Comment by steinoro** [comment]
Dette gjeld ALLE `README.md` til oppgåver i Scratch, Python, Web og Processing. Ordlyden er litt forskjellig frå fil til fil, men dei fleste har noko som liknar dette:
> - [ ] Eleven viser middels måloppnåelse ved å fullføre oppgaven.
> - [ ] Eleven viser høy måloppnåelse ved å videreutvikle egen kode basert på oppgaven, for eksempel ved å gjøre en eller flere av variasjonene nedenfor.

Eg (me) vil endre til teksten som står i hermeteikna over, inkludert lenka til lærardokumentet.

**Comment by teodorlu** [comment]
Har laget et [Pandoc-basert filter](https://github.com/teodorlu/codeclub-markdown-criteria-filter) som ser ut til å gi [forventet resultat](https://github.com/teodorlu/kodeklubben-oppgaver/commit/69456a88415c07e4c4d3ea9954e0ba4d0273fc21). Desverre skriver Pandoc om all Markdown den får inn, som gjør diffen noe lite lesbar.

Kan du se over og gi tilbakemelding på om dette var hva du ville ha?

**Comment by teodorlu** [comment]
@tjesi og jeg fant noen problemer med vårt Markdown-format gjennom Pandoc:

1. Tabeller blir formatert som ren tekst
2. YAML-header strippes ut
3. Problemer med enkelte kodeblokker

Ser ut som dette ikke er en løsning.

**Comment by arve0** [comment]
Du kan bruke [dette scriptet som utgangspunkt](https://github.com/arve0/codeclub_lesson_builder/blob/master/utils/fix_checklists.js).

Det fungerer slik som dette:

1. les inn alle filer
2. søk etter tekst / mønster i teksten
3. bytt ut ønsket tekst
4. skriv tilbake til filen

En kan også titte i `fix_code_blocks.js` og `fix_indentation.js` som ligger i samme mappe.

**Comment by teodorlu** [comment]
Personlig vurdering: dette var vanskeligere å få til automatisk enn jeg trodde. Mulig det hadde vært lettere med en ren finn-erstatt-tilnærming.

Lukker derfor denne. Uenig? Åpne igjen.
