### ISSUE TITLE
Problem med Scratch: Flaksefugl

### ISSUE THREAD

**Issue by moldeklev** [kodeklubben/oppgaver#596]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/flaksefugl
Oppgave: http://oppgaver.kidsakoder.no/scratch/flaksefugl/flaksefugl.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Får feilmelding når jeg skal laste ned som pdf. Har prøvd både i Explorer og Chrome.

**Comment by gahjelle** [comment]
Jeg opplever det samme. Noe har nok gått galt siste gang siden ble bygget. PDF for andre oppgaver det ut til å funke (jeg testet bare et par andre tilfeldig valgte oppgaver).

@arve0: ønsker du å se om det er noen underliggende årsak eller skal jeg bare patche det opp?

**Comment by gahjelle** [comment]
@moldeklev Tusen takk for tilbakemeldingen!

**Comment by arve0** [comment]
@gahjelle Jeg kjører et manuelt bygg i løpet av kvelden.

**Comment by gahjelle** [comment]
Da skal PDF'en for Flaksefugl virke igjen (https://github.com/kodeklubben/kodeklubben.github.io/pull/18)

**Comment by moldeklev** [comment]
Tusen takk, kjapt levert :)


mvh
Rolf-Anders Moldeklev

2017-08-23 12:51 GMT+02:00 Geir Arne Hjelle <notifications@github.com>:
