### ISSUE TITLE
Problem med Processing: Farger

### ISSUE THREAD

**Issue by VebjornBK** [kodeklubben/oppgaver#598]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/processing/farger
Oppgave: http://oppgaver.kidsakoder.no/processing/farger/farger.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.
I denne oppgaven burde det spesifiseres at variablen skal være utenfor både void setup() og void draw()

**Comment by teodorlu** [comment]
Enig. Mottar gjerne Pull Request.

Teodor
