### ISSUE TITLE
Elm: Skrive om oppgaver til å bruke Ellie

### ISSUE THREAD

**Issue by teodorlu** [kodeklubben/oppgaver#609]
Den største terskelen for Elm-kurset er håndtering av filer. Vi ender opp med å kopiere ting hit og dit, og dersom ikke alt kommer med, blir noe feil.

[Ellie](ellie-app.com) er nå i stand til å gjøre alt en god lokal editor kan gjøre. Vi kan linke til en ferdig editor med kode vi spesifiserer. Vi kan for eksempel linke [direkte til en editor med SVG-kode](https://ellie-app.com/L6BYddKPa1/0).

Å skrive om en av de eksisterende oppgavene til å bruke Ellie er en fin introduksjon til nye bidragsytere.

Høres det spennende ut? Jeg svarer på spørsmål + gir tilbakemelding på kode!

**Comment by mortenaa** [comment]
Hei @teodorlu jeg kan godt ta denne oppgaven

**Comment by mortenaa** [comment]
Er det meningen at de omskrevne oppgavene skal erstatte de gamle, eller skal de være et alternativ?

Får ikke assignet heller. Må kanskje legges til som Collaborator?

**Comment by teodorlu** [comment]
*Er det meningen at de omskrevne oppgavene skal erstatte de gamle, eller skal de være et alternativ?*

Jeg ønsker minst mulig potensiell forvirring i kurset. Erfaringsmessig var det lite verdi å hente i å ha et lokalt utviklingsmiljø. Jeg synes vi bør standardisere på Ellie. Vi kan gjerne ha en oppgave som gjør rede for hvordan man kan utvikle lokalt, men det bør ikke komplisere de andre oppgavene.

Jeg ønsker ikke å ha så mye å si på hvordan vi gjør dette at du blir hindret.

Hvis du tilfeldigvis er stasjonert i Oslo, kan vi godt ta en prat over en kaffe.

*Får ikke assignet heller. Må kanskje legges til som Collaborator?*

Jeg har lagt deg til nå. Prøv igjen!

**Comment by mortenaa** [comment]
Ok, den er grei. Er lokalisert i Oslo, så den kaffen får vi ta ved en annen anledning. Jeg var forøvrig også på Oslo Elm Day i fjor :-)

Får fortsatt ikke assignet issue :-(

**Comment by teodorlu** [comment]
Da fikk jeg assignet!

Foreslår at du begynner med oppgavene om [funksjoner](http://oppgaver.kidsakoder.no/elm/02_funksjoner_elm_repl/02_funksjoner_elm_repl.html) og [moduler](http://oppgaver.kidsakoder.no/elm/03_moduler_elm_reactor/03_moduler_elm_reactor.html).

Lokal installasjon trenger du ikke ta hensyn til, anta kun bruk av Ellie. Guide for hvordan å sette opp et lokalt utviklingsmiljø kan vi heller vurdere en dedikert oppgave til seinere.

**Comment by mortenaa** [comment]
Er i gang med funksjoner oppgaven. Den må omskrives en god del, siden mye som gjøres i REPL ikke kan gjøres i Ellie. 

Men moduler oppgaven ser jeg ikke helt hvordan vi får gjort i Ellie, siden alt må være i samme "fil"

**Comment by teodorlu** [comment]
Ser hva du mener. Er kanskje ikke mye igjen av oppgaven om vi fjerner alt lokalt. Og som du sier, kan vi ikke programmere moduler med Ellie ennå.

Mulig det er bedre å samle opp hva som er igjen av nytteverdi fra de første oppgavene, og så flytte det som er relatert til lokale filer inn i en egen oppgave.

**Comment by mortenaa** [comment]
Har skrevet om funksjoner oppgaven til å bruke Ellie. Om dette ser greit ut kan jeg fortsette med de andre oppgavene. 

En PR per oppgave som skal konverteres til Ellie, eller skal vi oppdatere denne etter hvert som jeg konverterer de andre oppgavene? @teodorlu

**Comment by tjesi** [comment]
@teodorlu og @mortenaa : hva er status her?

**Comment by teodorlu** [comment]
Arbeidet er inne på master, så denne kan lukkes.
