### ISSUE TITLE
Problem med Python: Hvor gammel er du?

### ISSUE THREAD

**Issue by trastad** [kodeklubben/oppgaver#611]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/hvor_gammel_er_du
Oppgave: http://oppgaver.kidsakoder.no/python/hvor_gammel_er_du/hvor_gammel_er_du.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Hei!
Jeg får ikke skrive inn bokstaver i input feltet. Får beskjed NameError: name ´ja´is not defined. Hvis jeg skriver tall så fungerer det. 
Jeg jobber på ipad med appen SketchPython. Forslag til bedre apper mottas med takk :-)

**Comment by gahjelle** [comment]
Hei, og tusen takk for tilbakemeldingen!

En NameError i Python får man typisk om man prøver å bruke en variabel som ikke er definert (ofte fordi python tror at noe som ikke skal være en variabel er det).

Siden du her får melding om at variabelen `ja` ikke er definert vil jeg gjette på at `ja` blir tolket som en variabel i stedet for en tekststreng i if-testen din? I såfall kan du legge fnutter rundt `ja` for at det skal bli tolket som en tekst. Altså du må skrive `'ja'` i stedet for `ja`.

Håper det hjelper deg videre?

Geir Arne

**Comment by gahjelle** [comment]
Jeg har ikke ipad selv og kjenner ikke til noen gode apper for python til den. Men du kan prøve om du synes noen av "python på nettside"-stedene fungerer bedre for deg?

Jeg har brukt https://trinket.io litt selv. Du trenger ikke konto for å teste. Litt ned på siden vil du se tre sirkler og en skilpadde. På telefonen må jeg trykke på blyant-ikonet for å se eksempel-koden og skrive min egen, men på større skjermer får du kanskje opp koden ved siden av sirklene? Du kan endre litt i eksempel-koden eller fjerne den helt for å skrive egen. Trykk deretter play-trekanten for å kjøre koden.

**Comment by gahjelle** [comment]
En annen tilsvarende nettside som jeg ikke har prøvd selv men som ser lovende ut er repl.it: https://repl.it/languages/python3

**Comment by trastad** [comment]
Takk for hjelpen. Det fungerte helt fint.

Når det gjelder bruk av nettsider til koding så har jeg forsøkt litt med Scratch. Den siden jeg får opp via kidsakoder krever Flash, noe iPaden ikke er veldig glad i. Prøver å bruke nettleseren puffin og da får jeg jobbet litt, men den har ikke kontakt med tastaturet så det blir en del rare resultater. Foreløpig ser det ut som SketchPython fungerer greit, men den takler ikke norsk alfabet så i oppgaven med hemmelig kode brukte jeg engelsk alfabet og det fungerte helt fint.

Mvh Trude Høgstedt
Tråstad Ungdomsskole

5. nov. 2017 kl. 11:31 skrev Geir Arne Hjelle <notifications@github.com<mailto:notifications@github.com>>:


Hei, og tusen takk for tilbakemeldingen!

En NameError i Python får man typisk om man prøver å bruke en variabel som ikke er definert (ofte fordi python tror at noe som ikke skal være en variabel er det).

Siden du her får melding om at variabelen ja ikke er definert vil jeg gjette på at ja blir tolket som en variabel i stedet for en tekststreng i if-testen din? I såfall kan du legge fnutter rundt ja for at det skal bli tolket som en tekst. Altså du må skrive 'ja' i stedet for ja.

Håper det hjelper deg videre?

Geir Arne

**Comment by gahjelle** [comment]
Ja, flash gjør Scratch litt slitsomt å bruke på nettbrett. Du kan teste Snap, http://snap.berkeley.edu - Dette er et språk basert på Scratch men som kjører i javascript slik at det virker bedre på nettbrett. Siden er kanskje ikke like brukervennlig som Scratch, men on du har gjort litt Scratch lenger du igjen det meste!

Lykke til!

**Comment by gahjelle** [comment]
Jeg stenger dette issue't siden vi har løst det originale problemet 😊
