### ISSUE TITLE
ComputerCraft: Sprettball - syntax-feil

### ISSUE THREAD

**Issue by okkero** [kodeklubben/oppgaver#612]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/computercraft/sprettball
Oppgave: http://oppgaver.kidsakoder.no/computercraft/sprettball/sprettball.html

Det ser ut til å være en syntax-feil i den første kodesnutten i steg 5:
```lua
X = X - [ ] fartX                         -- ny linje
Y = Y - [ ] fartY                         -- ny linje
```
Disse klammene ser ut som de ikke skal være der, og i neste kodesnutt er disse linjene endret til:
```lua
X = X + fartX
Y = Y + fartY
```

Virker som det siste er rett, og at den første snutten må endres.

**Comment by okkero** [comment]
Tok en titt på historikken. Ser ut som dette er et resultat av et "search-and-replace" som har erstattet litt mer en det skulle.

**Comment by gahjelle** [comment]
Ja, der har plussen blitt tolket som en markdown-liste og gjort om til en checkbox ... Takk for fiksen!
