### ISSUE TITLE
Forslag til ny læringskilde!

### ISSUE THREAD

**Issue by gluntn** [kodeklubben/oppgaver#616]
Vet ikke om dette er rette plassen for det, men holder på å lære meg JavaScript og kom over denne: https://javascript30.com/

Koster ingenting (du må dog lage en bruker) og du lærer deg JavaScript gjennom eksempler! Krever noe forkunnskap med JS (og ES6), men synes ellers den er bra (er selv på dag 4). 👍

**Comment by teodorlu** [comment]
Hei!

Synes oppgavene så fornuftige ut. Moderne jravascript uten en masse rammeverk er nyttig kunnskap.

Har du noen tanker om hvordan vi kan bruke den på oppgavesiden? Som basis for å oversette oppgaver? Eller noe annet?

Teodor
