### ISSUE TITLE
Problem med Python: Skilpaddeskolen

### ISSUE THREAD

**Issue by LukasKrogh** [kodeklubben/oppgaver#621]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/skilpaddeskolen
Oppgave: http://oppgaver.kidsakoder.no/python/skilpaddeskolen/skilpaddeskolen.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

### Bruker Windows 10, Ser på oppgaven med Google Chrome og her er koden:

from turtle import *

def poly(sides, length):
    angle = 360/sides

    for n in range(sides):
       for num in range(8):
        forward(length/16)
        penup()
        forward(length/16)
        pendown()
        
def dashpoly(sides, length):
        angle = 360/sides

        for n in range(sides):
        dashforward(length)
        right(angle)
        
poly(4, 100)
right(180)
pencolor("blue")
poly(3,150)

**Comment by gahjelle** [comment]
Hei Lukas. Det er litt vanskelig å se fra koden som er limt inn her om innrykkene er riktige. Men en grei tommelfingerregel er at etter hver linje som avsluttes med et kolon skal neste linje rykkes inn med 4 ekstra mellomrom.

For eksempel skal det være:

    def poly(sides, length):
        angle = 360/sides

Tilsvarende skal det være 4 ekstra mellomrom etter hver av `for`-linjene. Feilmeldingen tilsier at du har en linje som ikke er rykket inn riktig etter et kolon.

Håper det hjelper deg videre!

Geir Arne
