### ISSUE TITLE
Problem med 'Scratch: Julekort'

### ISSUE THREAD

**Issue by troelswh** [kodeklubben/oppgaver#626]
Oppgave: http://oppgaver.kidsakoder.no/beta/scratch/julekort/julekort
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/julekort

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Hei,

Det er et antall bilder på sida som ikke laster og det gjør det vanskelig å bruke dette opplegget. Se skjermbilde under som viser hvilke bilder som gir 404 feil.

Jeg fant en PDF med opplegget (https://iktipraksis.iktsenteret.no/sites/default/files/julekort-i-scratch.pdf) men håper nettsida kan fikses også.

Mvh
Troels

![image](https://user-images.githubusercontent.com/34675986/34148453-87df650a-e4a1-11e7-9573-2b0112c4debd.png)

**Comment by teodorlu** [comment]
Testet live nettopp, ser ut til å være i orden igjen. Takk for beskjed!
