### ISSUE TITLE
Problem med Web: HTML: Publiser nettsiden din

### ISSUE THREAD

**Issue by anarth1609** [kodeklubben/oppgaver#630]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/web/publiser
Oppgave: http://oppgaver.kidsakoder.no/web/publiser/publiser.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.
Dere har gjort alt på en mac som gjør at de som bruker windows pc-er ikke forstår alt. F.eks. fikk jeg ikke publisert nettsiden min. Jeg tror denne "artikkelen" har blitt for gammel. Dere bør også oppdatere den.

**Comment by Rotekoppen** [comment]
Jeg mener at oppgaven er helt oppdatert, han har brukt mac/linux, men det er beskrevet slik at en med windows kan forstå...

**Comment by anarth1609** [comment]
Jeg forstod ikke bare hvordan man publiserer web/hjemmesiden sin. Kan du prøve å forklare sånn at jeg forstår.


________________________________
Fra: Rotekoppen <notifications@github.com>
Sendt: 29. desember 2017 08:55:48
Til: kodeklubben/oppgaver
Kopi: Anarththan Achshathan Muruganandan; Author
Emne: Re: [kodeklubben/oppgaver] Problem med Web: HTML: Publiser nettsiden din (#630)


Jeg mener at oppgaven er helt oppdatert, han har brukt mac/linux, men det er beskrevet slik at en med windows kan forstå...

**Comment by Rotekoppen** [comment]
Med å se nermere på dette er den litt utdatert, spesielt delen med "Github-Desktop"

Først, det kan være lurt å bruke skrivebordet i stedet for dokumenter.

Følg hele oppgaven helt til han åpner mappen på skrivebordet, men ignorer:
```
Hvis du er vant til å bruke kommandolinjen til Linux eller Mac OS X, så kan du gjøre det som står under ...or create a new repository on the command line.
```
I stedet for "tillat" kan det dukke opp andre alternativer, bare velg Ja/aktiver/Godta/Tillat.

- Legg "html" -filen din i mappen på skrivebordet.

- Gi den navnet "index.html"

Trenger du en eksempelfil kan du bruke denne som er hentet fra mr.doob.
[Pakk-Ut.zip](https://github.com/kodeklubben/oppgaver/files/1594768/Pakk-Ut.zip)

Følg "Oppdater ditt-brukernavn.github.io
I stedet for "compare", må du velge "html" -filen dine i sjekklisten, og i stedet for publish, trykker du på Push origin (Plassert høyt oppe i github klienten)

**Comment by teodorlu** [comment]
Hei!

@anarth1609: takk for tilbakemeldinger på oppgaven.
@Rotekoppen: takk for forklaringshjelp.

Hvis vi skal kunne gjøre oppgaven bedre, må vi ha konkrete tilbakemeldinger. Akkurat hva fungerte ikke? Hvor langt kom du? At oppgaven er generelt for dårlig er vagt.

Jeg er enig med @Rotekoppen om at dette ikke er en generelt dårlig oppgave. Tar dog endringsforslag på Pull Request.

Med det lukker jeg denne. Åpne igjen ved ny informasjon.

Teodor
