### ISSUE TITLE
Problem med Python: Repetisjon

### ISSUE THREAD

**Issue by ILoveRedPandas** [kodeklubben/oppgaver#634]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/repetisjon
Oppgave: http://oppgaver.kidsakoder.no/python/repetisjon/repetisjon.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

name = "Ada"
if name == "Per":
    print("Per er et guttenavn")
elif name == "Ada":
    print("Ada er et jentenavn")
elif name == "Kim":
    print("Kim kan være både guttenavn og jentenavn.")
else:
    print("Jeg vet ikke om " + navn + " er en gutt eller ei jente.")

Det skal stå Name og ikke navn i 

else:
    print("Jeg vet ikke om " + navn + " er en gutt eller ei jente.")

**Comment by tjesi** [comment]
Hei @ILoveRedPandas , takk for at du gir beskjed! Eg har nå endret oppgaven, slik at dette blir rettet opp neste gang vi oppdaterer nettsidene. - Tjerand
