### ISSUE TITLE
Problem med Python: Lister og indekser

### ISSUE THREAD

**Issue by tskauli** [kodeklubben/oppgaver#635]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/lister_og_indekser
Oppgave: http://oppgaver.kidsakoder.no/python/lister_og_indekser/lister_og_indekser.html

Denne oppgaven, og flere andre, bruker fagordet "streng" uten forklaring, mens ordet "indeks" blir forklart.

Enten bør "streng" forklares, eller så kan det omskrives med "tekst". Dette gjelder også for flere andre oppgaver.

**Comment by teodorlu** [comment]
Jeg er enig. Streng har ingenting å gjøre i programmeringskurs for norske barn.

**Comment by tjesi** [comment]
Løst i #993
