### ISSUE TITLE
Oppdater installasjonsbeskrivelse til siste versjon av Mincecraft

### ISSUE THREAD

**Issue by javaguruen** [kodeklubben/oppgaver#641]
"Oppgaven" Installering av ComputerCraft er ikke oppdatert til siste versjon av ComputerCraft og mye er endret i Minecraft Launcher slik at beskrivelsen ikke lenger er riktig for nyere versjoner av Minecraft

**Comment by teodorlu** [comment]
Lukker denne med merge av PR. @javaguruen: åpne igjen om det er mer du savner.
