### ISSUE TITLE
                 dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddProblem med Python: Stjerner og galakser

### ISSUE THREAD

**Issue by ThePanOfficial** [kodeklubben/oppgaver#644]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/stjerner_og_galakser
Oppgave: http://oppgaver.kidsakoder.no/python/stjerner_og_galakser/stjerner_og_galakser.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

**Comment by Rotekoppen** [comment]
Litt mange "d"er?
