### ISSUE TITLE
Problem med 'Web: Forsvunnet katt'

### ISSUE THREAD

**Issue by herdis** [kodeklubben/oppgaver#647]
Oppgave: http://oppgaver.kidsakoder.no/beta/web/forsvunnet_katt/forsvunnet_katt
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/web/forsvunnet_katt

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

I oppgaveteksten står det "slik som du lærte i forrige leksjon." Men om ein ser på oppgavene som ligger her, finst det bare ei nybegynneroppgave - denne fortsetter altså på ei anna oppgave som vi ikkje har inne. Løsningsalternativer: 1) få inn første oppg og lenke til den, 2) skriv om.

**Comment by tjesi** [comment]
Takk for beskjeden! Oppgaven det henvises til er [Introduksjon til web](http://oppgaver.kidsakoder.no/beta/web/introduksjon_til_web/introduksjon_til_web), som er en nybegynneroppgave som ligger på siden, og som ligger før denne oppgaven i spillelisten som heter HTML. Eg har nå oppdatert oppgaveteksten i "Forsvunnet katt", slik at den linker til den forrige oppgaven.
