### ISSUE TITLE
Problem med Scratch: Flaksefugl

### ISSUE THREAD

**Issue by malemuk** [kodeklubben/oppgaver#649]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/scratch/flaksefugl
Oppgave: http://oppgaver.kidsakoder.no/scratch/flaksefugl/flaksefugl.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Det mangler en forklaring på hvordan man styrer rekkefølget skriptene kjøres i. Flakse har 3 skripter som starter når man trykker på grønt flagg. Hvis disse ikke starter i riktig rekkefølge (skriptet som plasserer Flakse må kjøre før de andre), funker det ikke.

Dessuten en liten detalj: det hadde vært fint å forklare hvordan man endrer størrelsen på Flakse (det nevnes at det kan gjøres, men ikke hvordan).

**Comment by tjesi** [comment]
Skript kjøres vanligvis samtidig, høres ut som at programmet bare trengs å startes på nytt. Man endrer størrelse på figurer ved å trykke på forstørrelseglasset og så på figuren man ønsker å endre, som forklart på ulike måter i [Astrokatt](https://oppgaver.kidsakoder.no/scratch/astrokatt/astrokatt) og [Felix og Herbert](https://oppgaver.kidsakoder.no/scratch/felix_og_herbert/felix_og_herbert).
