### ISSUE TITLE
Inspirasjon for simuleringer fra fysikk og biologi fra Greenfoot

### ISSUE THREAD

**Issue by kjto** [kodeklubben/oppgaver#68]
Greenfoot er et visuelt læringsmiljø for å lære Java.  Introduksjonsboka inneholder flere eksempler på simuleringer fra fysikk og biologi, og det er mange som har videreutviklet. Det er alstå mulig å finne ideer og løsninger som kan gjenbrukes og gjenskapes i Scratch.

**Comment by arve0** [comment]
God ide, men ser ikke ut som vi har gjennomføringsevne på alle ideene våre 😄
