### ISSUE TITLE
Python funkskon vs prosedyre

### ISSUE THREAD

**Issue by torgeiws** [kodeklubben/oppgaver#69]
I oppgavesettet, særlig her: https://github.com/kodeklubben/oppgaver/blob/master/src/python/skilpaddeskolen/skilpaddeskolen.md#tips-protip blir det skilt mellom prosedyre og funksjon. Dette kunne rent hypotetisk vært relevant, men jeg tror egentlig ikke er noe grunn til at vi skal skille mellom disse. Det virker for meg som dette utelukkende er fagspråk som gir navn på forskjellig subrutiner avhengig av små detaljer som på ingen måte har innvirkning på forståelsen av konseptet vi ønsker å lære bort.

**Comment by arve0** [comment]
Enig i det! PR? :smile:

**Comment by arve0** [comment]
Takk :+1: 

De som gjenstår:
```
$ ack prosedyre -cl
python/hangman/hangman.md:1
python/skilpadder_hele_veien/skilpadder_hele_veien.md:4
python/skilpaddeskolen/skilpaddeskolen.md:4
python/tre_pa_rad/tre_pa_rad.md:7
python/tre_pa_rad_mot_datamaskinen/tre_pa_rad_mot_datamaskinen.md:12
```

**Comment by arve0** [comment]
Minus skilpaddeskolen som nettopp er fikset. Den har prosedyre i en tips-boks, men bruker funksjon i teksten.

**Comment by okpedersen** [comment]
Denne ser ut som den er ferdig? Lukke denne?

**Comment by arve0** [comment]
Ja.
