### ISSUE TITLE
Scriptcraft: Legge til oppsett

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#70]
Scriptcraftoppsett er oversatt av @fjukstad: https://gist.github.com/fjukstad/ab1cddc34adaee4deed7

Dette kunne vi laget et oppgavesett av.

**Comment by fjukstad** [comment]
:+1: @arve0 ! 

Har ikke fått testet ut oppsettet på kodeklubben her i Tromsø enda, men det blir på onsdag! Regner med vi finner noen småting som må rettes opp i etterhvert, men det er et sted å starte. Det hadde vært kjempekult å lage et oppgavesett med Scriptcraft. Har ikke så mye erfaring med det enda, men det kommer seg nok når vi får prøvd det ut litt! So far so good!

**Comment by arve0** [comment]
Se også responsen fra Seppe vanden Broucke på jython til canarymod (hvis dere har noen python kurs): https://github.com/Macuyiko/MinecraftPythonConsole/issues/6

**Comment by fjukstad** [comment]
Kult! Vi har kjørt python-kurs dette semesteret, men barna ville mye heller lære seg å lage plugins til Minecraft så nå prøver vi ut Scriptcraft. Skal ta en titt på repoet! :+1:

**Comment by Helgenen** [comment]
Veldig kult! Alt av Minecraft er veldig etterspurt blant barna.

søn. 8. mar. 2015 kl. 20.45 skrev Bjørn Fjukstad <notifications@github.com>:

**Comment by arve0** [comment]
Lukker, ettersom det ikke har vært aktivitet her på ett år.
