### ISSUE TITLE
Tillate pull requests på kodeklubbens wiki sider via travis

### ISSUE THREAD

**Issue by Oisov** [kodeklubben/oppgaver#710]
Slik det er per dags dato er det ikke mulig å legge inn pull requests på wiki sider. Dette er ønskelig fordi det arbeides med en kort wiki bidragsytere kan henvende seg til, her kan vel @tjesi bekrefte. [Ett uttkast finnes her](https://github.com/Oisov/oppgave/wiki).

Selv har jeg fått til dette med å legge in PR på wiki sidene med å opprette to repoer 
[*oppgave*](https://github.com/Oisov/oppgave) og [*oppgave-wiki*](https://github.com/Oisov/oppgave-wiki). Her inneholder *Oppgave-wiki* repoet alle filene på wikien og disse synches til wiki siden på *oppgave* repoet via **travis**.

[Hvordan dette kan gjøres, står glimrende forklart i denne guiden.](http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html)

Er dette noe som kan gjøres på kodeklubbens Github profil også? Kanskje @NorwegianKiwi har peiling?

**Comment by NorwegianKiwi** [comment]
Ja, dette synes jeg virker som en fin løsning. Vi kan lage et repo som heter `kodeklubben/oppgaver-wiki`, som da er wiki'en til `kodeklubben/oppgaver`.

**Comment by Oisov** [comment]
Da var dette i boks!
