### ISSUE TITLE
Problem med Web: JS: Hei JavaScript!

### ISSUE THREAD

**Issue by Mondayblues** [kodeklubben/oppgaver#787]
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/web/hei_js
Oppgave: http://oppgaver.kidsakoder.no//web/hei_js/hei_js.html

Beskriv ditt problem her. Ta gjerne med operativsystem, nettleser og eventuell kode du har skrevet.

Hei, godt voksen men man må begynne et sted. Jeg savner flere eksempler på hvordan koden skal se ut. Og da gjerne en skjermdump slik at man ikke bare får et utsnitt men også med hvor navn osv. Skal skrives inn manuelt og som en subjektiv variabel, jeg slet med å få dette til å virke uten noe hjelp fra noen som kan kode. 

Fint om dere forklarer nøyere om koden fra forrige oppgave skal slettes eller om det er en fortsettelse. 

Mvh. Vincent Stuestøl

**Comment by tjesi** [comment]
Hei Vincent,

Istedenfor skjermdump så viser vi koden steg for steg i grå ruter i oppgaven. Eksempler:

I steg 1 skriver vi "Skriv inn denne koden i fanen JavaScript:", og så viser deg hva du skal skrive.
I steg 2 skriver vi: "Slett koden din fra steg 1.", og så "Skriv inn denne koden:".
I steg 2 skriver vi også: "Koden til nå:", og da skal altså hele programmet se slik ut.

Håper dette var til hjelp :)
