### ISSUE TITLE
Python: Labyrint-spill

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#90]
Forslag til oppgave fra en av ungene:

V: "Og on_drag kan du bruke når musen beveger seg og museknappen holdes inne."
U: "Kult, kan man lage et maze-spill?"
V: "Hva er maze?"
U: "Slik labyrint."
V: "Klart det går ann!"

**Comment by okpedersen** [comment]
Jeg tenkte jeg skulle lage en oppgave som kan likne på denne: http://www.pygame.org/project-Rect+Collision+Response-1061-.html

Veldig enkelt med Pygame + Pygame Zero.

**Comment by arve0** [comment]
Lukker, ettersom det ikke har vært aktivitet her på ett år.
