### ISSUE TITLE
Organisere materiellet vårt

### ISSUE THREAD

**Issue by tjesi** [kodeklubben/oppgaver#92]
Nå er kodeklubben.github på vei til å bli en veldig bra arena for prosjektene våre, og vi burde tenke litt på hvordan vi ønsker å organisere materiellet vårt. Vi har laget mye bra selv på norsk, samt at det finnes mye bra der ute som er verdt å vise til, feks Kodegenet, CodeAcademy, Code.org og mer, noe som kan knyttes til det vi allerede har og mye utenom. Vi må finne en god måte å organisere alt dette på, slik at det er enkelt å finne frem.

Skal vi legge eksterne prosjekter til de kursene vi allerede har, også merke de som eksterne? Skal vi lage egne sider som går rett til eksterne ressurser? Skal vi samle alle eksterne ressurser under en side, eller flere sider ut ifra nivå?

Eg tenker det er viktig å fremheve:
- det vi har laget selv / er på norsk. 
- Kodetimen. 
- noe på hvert ferdighetsnivå.

Innspill?

**Comment by arve0** [comment]
I første omgang tror jeg det holder å skrive mer informasjon på hovedsiden, pluss fikse [intro.js](https://usablica.github.io/intro.js/) for å framheve det beste innholdet. Analytics viser vel at det er Scratch, Computercraft og Python som er vinnerne?

**Comment by tjesi** [comment]
Enig, introsiden burde oppdateres litt. Og teksten i index.md. CodeStudio vil bli populært etterhvert, så det bør også fremheves sammen med Scratch, Python og ComputerCraft.

Synes vi kun burde ha ett kurs i Python, ikke to. Og heller organisere materiellet bedre.

Skal vi lage en egen spillelist som heter "Ekstern", slik at alle lenker til oppgavesett legges der istedetfor blant det andre?

**Comment by arve0** [comment]
I latskapens tjeneste, hva med en [popover](http://embed.plnkr.co/m2J31e/preview)? Den kan i tillegg inneholde litt kort info. Samt smøre på et ikon over kurs-ikonet:

![skjermbilde 2015-10-06 kl 13 49 12](https://cloud.githubusercontent.com/assets/4810521/10307697/175f16b2-6c31-11e5-982b-73f558767bce.png)

**Comment by tjesi** [comment]
Det funker fett :)

Tjerand

6. oktober 2015 kl. 13.50 skrev Arve Seljebu <notifications@github.com>:

**Comment by arve0** [comment]
Vi har nå popup for eksterne ressurser og fremhevet kodetime.
