### ISSUE TITLE
Legge til github ribbon på side?

### ISSUE THREAD

**Issue by ArgTang** [kodeklubben/oppgaver#94]
Mange har link til github repoen fra wikien\siden sin. Vet ikke helt åssen jeg kan putte disse inn da de er i "vanlig" html

https://github.com/petethepig/github-ribbons-css
https://github.com/simonwhitaker/github-fork-ribbon-css (denne kan serveres via cdn)
https://codepo8.github.io/css-fork-on-github-ribbon/ (denne er embedded)

**Comment by arve0** [comment]
Trur en ribbon blir et forstyrrende element, kanskje en tekst i footer passer bedre? Det kan i så tilfelle legges til som YAML i index.md:

```
---
footer: "[Bidra?](https://github.com/kodeklubben/oppgaver)"
---
```

**Comment by ArgTang** [comment]
Ok, så lenge den blir lett å finne blir det bra

**Comment by arve0** [comment]
Fikset i #96 : `[Bidra?](https://github.com/kodeklubben/oppgaver)` i footer på index.md
