### ISSUE TITLE
Problem med 'Python: Kuprat'

### ISSUE THREAD

**Issue by bonesvoll** [kodeklubben/oppgaver#946]
Oppgave: http://oppgaver.kidsakoder.no//python/kuprat/kuprat
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/kuprat

Jeg testet oppgaven på Mac (Mojave), og ser at Mac fortsatt kommer med Python 2.7. Oppgaven slik den er lagt opp krever Python 3. 
F.eks. vil man i Python 2 måtte erstatte:
`navn = input('Hva heter du? ')
`
med
`navn = raw_input('Hva heter du? ')
`
Jeg synes vi skal holde oss til Python 3, men vi bør få med informasjon om dette i oppgaven.

**Comment by TacoCode1** [comment]
Dette er et godt poeng. Om du lager en fork, legger det til, og lager en pull request, så kan det hende det blir godtatt

**Comment by lexnederbragt** [comment]
Dette gjelder flere oppgaver (teller 7 i farten). Jeg tror det ville vært bedre å finne en måte på å varsle generelt om at oppgavene forutsetter python 3, og om man har python 2 at man må ta hensyn til dette, og eventuelle andre forskjeller.

**Comment by tjesi** [comment]
Har merget Lex sin commit, hvor vi skriver at vi bruker Python 3 som generell informasjon om alle oppgavene. Lukker dermed denne.
