### ISSUE TITLE
Lenke til Bebras

### ISSUE THREAD

**Issue by herdis** [kodeklubben/oppgaver#947]
Kan nokon tilpasse logoen til Bebras (svartkvit som dei andre) og få den inn som lenke til eksterne ressurser på https://oppgaver.kidsakoder.no? 
![bebras bilde](https://user-images.githubusercontent.com/4460320/47426928-0640b800-d78f-11e8-8629-87788f0f8c00.png)

Den skal lenke til: https://www.bebras.no/

**Comment by steinoro** [comment]
Fungerer dette biletet? Brukte Gimp. Fjerna fargene (til svart-kvit) og så auka eg kontrasten til maks for å få berre svart og kvitt.

![bebras](https://user-images.githubusercontent.com/27889905/60615755-69272c00-9dbf-11e9-907b-1c76f3359bee.png)

**Comment by tjesi** [comment]
Har du mulighet til å lage en hvit logo også? Altså bytte om på svart og hvit i denne.

**Comment by steinoro** [comment]
Negativ Bebras-logo
![bebras_negativ](https://user-images.githubusercontent.com/27889905/60626193-88cb4e00-9dd9-11e9-99f7-1fdc310c5ca4.png)

**Comment by tjesi** [comment]
Denne er nå løst i #1017
