### ISSUE TITLE
Problem med 'Python: Bokstaver'

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#949]
Oppgave: http://oppgaver.kidsakoder.no//python/bokstaver/bokstaver
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/bokstaver

Lenken til Skilpadder i introduksjonen fungerer ikke fra kursoversikten. For å reprodusere:

1. Gå til Python-kurset.
2. Klikk på i-ikonet til Bokstaver.
3. Klikk på lenken til Skilpadder.

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/4810521/48254037-1e5c3c80-e409-11e8-8838-c726170ed641.png">

**Comment by steinoro** [comment]
Så vidt eg kan forstå er det fordi me lagar lenka som `[Skilpadder](../skilpadder/skilpadder.html)`. Altså går me ut av Python-mappa når den brukast på kurssida, men den fungerer fint når me klikkar lenka inne i oppgåva. Det same problemet oppstår for alle oppgåver som har slike lenker i introduksjonen.

**Comment by tjesi** [comment]
En fiks kan være å skrive eksplisitt url for alle lenker som oppgis i introduksjonen i en oppgave... med mindre @Skagevang har en generell fiks på dette?

**Comment by Skagevang** [comment]
Ja har ingen god løsning akkurat nå, siden tooltips bare henter htmlen til oppgaven som en tekst. Så å ha en hel URL til oppgaven er jo en løsning. Går jo an å lage en sjekk med RegEx om det er en link inni introduksjonen og endre dette? Vet ikke hva du tenker? Om man bare skal endre litt på introduksjonen i denne og lage et issue i codeclub-viewer?

**Comment by tjesi** [comment]
Dette gjelder så få oppgaver at eg tenker vi bare kan løse det manuelt. Lager en PR.

**Comment by tjesi** [comment]
Løst.
