### ISSUE TITLE
.py blir rendret som lenker

### ISSUE THREAD

**Issue by arve0** [kodeklubben/oppgaver#950]
Filen https://github.com/kodeklubben/oppgaver/blob/master/src/python/index.md inneholder teksten helloworld.py, som blir rendret som en lenke.

**Comment by lexnederbragt** [comment]
Jeg har sjekket Safari, Chrome og Firefox på Mac, og der vises `helloworld.py` ikke som lenke. Er det andre browsere/operativ systemer som har dette problemet?

**Comment by tjesi** [comment]
Eg har sjekket Safari, Chrome og Firefox på Mac, og der vises helloworld.py som lenke...

**Comment by arve0** [comment]
> Eg har sjekket Safari, Chrome og Firefox på Mac, og der vises helloworld.py som lenke...

Som er selve feilen 🙂 Det skal _ikke_ vises som lenke, ettersom teksten _ikke_ er en lenke.

**Comment by arve0** [comment]
curl bekrefter samme som tjesi skriver:

```sh
$ curl -s https://oppgaver.kidsakoder.no/python | sed -e 's/>[ ]*</>\n</g' | grep helloworld.py
<p>Gi programmet ditt navnet <a href="http://helloworld.py">helloworld.py</a> og lagre det i den mappen du ønsker.</p>
```

**Comment by tjesi** [comment]
noen ide om hvordan vi får fikset dette? (@Skagevang )

**Comment by arve0** [comment]
Det fikses slik som dette: https://github.com/arve0/codeclub_lesson_builder/blob/6005ab6b009f287314d7c6dc27f0d6ffeba480ec/markdown.js#L38
