### ISSUE TITLE
To nye oppgaver

### ISSUE THREAD

**Issue by herdis** [kodeklubben/oppgaver#951]
Thomas Kjeldahl Nilsson har laga to oppgaver som har funka på kodeklubben sin, Kodeklubben Auli: 

https://docs.google.com/presentation/d/1yj3KneURqbrrE4H7LqHCuXnvStKdz02kkZwUHPf_ICk/edit?fbclid=IwAR1E4Lk9q-1TO0yXLeL_aOFuJ4Zz5a7b-D-9rRlCpmBfw57oZ9klAGivibk#slide=id.p

https://docs.google.com/document/d/1nnq0g8eV4ez1uZKBCuqyef-wBC6mLMCt65hoOaKZ_jk/edit?usp=sharing

Fint om de kan legges inn i oppgavesidene våre

**Comment by tjesi** [comment]
Publisert.
