### ISSUE TITLE
Feil år på en oppgave

### ISSUE THREAD

**Issue by TacoCode1** [kodeklubben/oppgaver#953]
På python- oppgaven med tittel "Hvor gammel er du?", så står det:

"Lag to variabler som du selv gir navnet på. Den ene variabelen skal være dette året, altså 2016. Den andre variabelen skal være året du ble født i."

Der det står "Den ene variabelen skal være dette året, altså 2016", men året skal endre seg utifra hvilket år det faktisk er, med å bruke noe js. Dette funker ikke. Jeg er ikke god i js, så jeg vet ikke hvordan dette fikses. 

Kan noen ordne det?

**Comment by TacoCode1** [comment]
Det er godt mulig at dette er på flere oppgaver, dette har ikke jeg sjekket. God jul forresten!

**Comment by lexnederbragt** [comment]
Nynorsken har 2018. Det ligger noe (java?)script i https://github.com/kodeklubben/oppgaver/blob/master/src/python/hvor_gammel_er_du/hvor_gammel_er_du.md som betyr at kanskje meningen er at året oppdateres automatisk i html versjonen, men det ser ikke ut til å virke. Året 2016 er også lagt inn i eksempelskriptet https://github.com/kodeklubben/oppgaver/blob/master/src/python/hvor_gammel_er_du/alder.py.

Det beste hadde vært om året ikke var kodet inn i oppgaven, for eksempel ved at brukeren også bes om hva dette året er via input.

**Comment by tjesi** [comment]
Oppklart i #1012
