### ISSUE TITLE
Problem med 'Python: Diffie-hellman'

### ISSUE THREAD

**Issue by TacoCraftxD** [kodeklubben/oppgaver#955]
Oppgave: http://oppgaver.kidsakoder.no//python/diffie-hellman/diffie-hellman
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/diffie-hellman

Underveis i oppgaven, spesifikt første punkt i "Steg 5: Bruke større parametre", står det: "Finn fram koden din fra Primtall og effektivitet, og legg den til å fila vi jobber med. Den skal nå se slik ut:" og det refereres til kode. 
Problemet er at der det står "Primtall og effektivitet" er det en lenke. Denne lenken leder til en 404 error. 

Hele "Diffie-hellman" oppgaven kommer også før "Primtall og effektivitet", så det er lite sannsynlig at de som jobber med "Diffie-hellman" oppgaven har gjort "Primtall og effektivitet" oppgaven.

Løsning: Bytte plass på oppgavene, og fikse lenken

**Comment by TacoCraftxD** [comment]
Det viser seg at lenken leder til [https://oppgaver.kidsakoder.no/python/primtall/primtall.md](https://oppgaver.kidsakoder.no/python/primtall/primtall.md), når den egnetlige lenken er [https://oppgaver.kidsakoder.no/python/primtall/primtall](https://oppgaver.kidsakoder.no/python/primtall/primtall)

**Comment by steinoro** [comment]
I oppgåvesamlinga "Kodeknekking" står Primtall før Diffie-Hellman. Det står også i introduksjonen til oppgåva at ein bør ha gjort Primtall fyrst (i alle fall repetere det ein gjer i oppgåva).

**Comment by tjesi** [comment]
Fikset i #1013 .
