### ISSUE TITLE
Problem med 'Python: Sprettball'

### ISSUE THREAD

**Issue by hausnes** [kodeklubben/oppgaver#960]
Oppgave: http://oppgaver.kidsakoder.no//python/sprettball/sprettball
Oppgavens kildekode: https://github.com/kodeklubben/oppgaver/tree/master/src/python/sprettball

Vår erfaring er at ved alle eksempel som inkluderer PGZ krever meir kode for å fungere enn det som står oppført. Eg og mine elevar (ulike Windows 10- og MacOS-versjonar, med Python 3.7-pakken, IDLE og PGZero) må i alle fall ha med:
`import pgzrun`
og avslutte med:
`pgzrun.go()`

**Comment by tjesi** [comment]
Oppgavene er oppdatert.
