### ISSUE TITLE
Synliggjøre oppgaver tilpasset Scratch 3

### ISSUE THREAD

**Issue by lexnederbragt** [kodeklubben/oppgaver#969]
Kunne det vært en ide å vise på en eller annen måte på https://oppgaver.kidsakoder.no/scratch at en oppgave er tilpasset Scratch 3?

**Comment by tjesi** [comment]
Vi planlegger å oppdatere hele siden til Scratch 3 i sommer, og dermed oppdatere alle oppgavene også. Vi trenger dermed ikke eksplisitt skille på oppgaver som passer Scratch 2 vs Scratch 3.
