### ISSUE TITLE
Python file -> new file

### ISSUE THREAD

**Issue by torgeiws** [kodeklubben/oppgaver#97]
Oppgavesettet sier at man skal trykke file -> new window for å åpne et nytt vindu for å skrive programmer. I realiteten finnes ikke new window i menyen. Riktig tekst er file -> new file.

Relevant oppgave: Skilpadder.

**Comment by arve0** [comment]
Ser ut som dette er noe som henger etter Python 2.7. 

![](http://echorand.me/site/notes/_images/open_new_window.png)

Vi må selvfølgelig rette oss inn etter 3.4, ettersom det er versjonen vi anbefaler.

**Comment by torgeiws** [comment]
Som en tilleggsopplysning kan jeg si at jeg har python 2.7.10, og jeg ser også New File.

**Comment by arve0** [comment]
Gjelder også:
src/python/kuprat/kuprat.md
src/python/mattespill/mattespill.md
src/python/skilpaddeskolen/skilpaddeskolen.md

Foreslår at vi fjerner alle henvisninger til "New Window" og benytter kun "New File".

**Comment by gahjelle** [comment]
Ser de fikset dette i England for en stund tilbake, https://github.com/CodeClub/python-curriculum/pull/42

Ble sikkert oppdatert til 3.3 og 2.7.n for en eller annen n <= 10? Enig i at vi bruker `New File` konsistent overalt.
