### ISSUE TITLE
'gjenta for alltid' vs 'for alltid'

### ISSUE THREAD

**Issue by lexnederbragt** [kodeklubben/oppgaver#970]
Jeg underviste Straffespark sist helg og oppdaget at 'for alltid' bokmålsblokken i som brukes oppgaven nå heter 'gjenta for alltid' på bokmålsvarianten av scratch.mit.edu. I Nynorskvarianten heter blokken fortsatt 'for alltid'.

Hvis det er en god grunn for denne forskjellen mellom bokmål og nynorsk slik at den bør beholdes må bokmålsoppgavene på GitHub tilpasses. Ellers kan kanskje bokmålsvarianten på scratch.mit.edu settes tilbake til 'for alltid'. 

_På den andre siden_ er det andre 'gjenta' blokker:  'gjenta til'  og 'gjenta (x) ganger', og dermed er det trolig en god ide å bruke 'gjenta for alltid'. (I den engelske varianten brukes 'repeat' og 'for ever', som kanskje burde blitt 'repeat forever')

**Comment by tjesi** [comment]
Ser ikke at det er noen gode grunner for å ha det forskjellig på bokmål og nynorsk. "gjenta for alltid" høres passende ut, og burde brukes på begge språkformer.

**Comment by tskauli** [comment]
Det er rettet til "gjenta for alltid" på nynorsk nå. Kommer live i løpet av uka.

**Comment by lexnederbragt** [comment]
Takk! Da går vi for 'gjenta for alltid' på både bokmål og nynorsk.
