### ISSUE TITLE
Islandsk språk

### ISSUE THREAD

**Issue by steinoro** [kodeklubben/oppgaver#980]
Eg har så smått begynt å omsette oppgåver til islandsk. Dette tek tid, og krev ekstra kvalitetskontroll, sidan eg ikkje er heilt stødig.

Er det noko spesielt som må på plass før me kan ha støtte for islandsk i oppgåvesamlinga?

**Comment by tjesi** [comment]
Vi trenger en språk-fil for GUI ala følgende oversatt til islandsk: https://github.com/kodeklubben/oppgaver/blob/master/filtertags/translation_nb.yml.

**Comment by steinoro** [comment]
Så når #978 er kvalitetssikra og godkjent er me good to go?

**Comment by tjesi** [comment]
Vi må også legge inn Islands som språk her: https://github.com/kodeklubben/oppgaver/blob/master/filtertags/keys.yml

**Comment by tjesi** [comment]
Vi trenger også en språk-fil for GUI til selve nettstedet oversatt til islands. Ala denne: https://github.com/kodeklubben/codeclub-viewer/blob/master/src/constants/captions_nb.js

**Comment by tjesi** [comment]
Til slutt trenger vi et islands flagg i i følgende mappe: https://github.com/kodeklubben/codeclub-viewer/tree/master/src/assets/graphics.

**Comment by tjesi** [comment]
Islands er nå tilgjengelig på siden.
