### ISSUE TITLE
Astrokatt - Start nytt prosjekt

### ISSUE THREAD

**Issue by connietg** [kodeklubben/oppgaver#981]
I oppgaven går man ut ifra at brukeren allerede er logget inn i Scratch når de skal åpne et nytt prosjekt. De aller fleste starter med Scratch uten en bruker. Jeg vil foreslå at det beskrives hvordan man åpner et prosjekt når man er inne i Scratch (Fil->Ny)

**Comment by tjesi** [comment]
Løst.
