### ISSUE TITLE
Språklige endringer Scratch 2 til 3

### ISSUE THREAD

**Issue by lexnederbragt** [kodeklubben/oppgaver#982]
På LKK arbeidslørdagen 11. mai begynte vi med en liste av språklige endringer mellom Scratch 2 og Scratch 3. Listen ligger her: https://docs.google.com/document/d/1SOdtnlk35XUqVlp2wWXUddsGZ9EzYkLUbppRYcYRegc/edit

Vi tar gjerne i mot flere om vi har glemt noe!

**Comment by tjesi** [comment]
Oppdateringer jobbes med i bl.a. #984 , #992 og #1016

**Comment by steinoro** [comment]
Ligg ei rekkje PR på vent, alle Scratch-oppgåvene skal vere oppdaterte både på bokmål og nynorsk.

**Comment by tjesi** [comment]
Ser ut som om alle oppgaver er oppdatert nå. Lukker denne.
