### ISSUE TITLE
yarn + node 10.16

### ISSUE THREAD

**Issue by lexnederbragt** [kodeklubben/oppgaver#994]
Jeg følgte instruksjonene på https://github.com/kodeklubben/oppgaver/wiki/Bygge-oppgavesidene-lokalt men fikk en feilmelding når jeg kjørte `yarn` for første gang:

```
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Wiki siden sier 

> prøv å slette `node_modules`-mappen og kjør `yarn` igjen for å installere det på nytt.

Jeg fant `/usr/local/lib/node_modules` og flytter `node_modules` mappen til et annet sted. Men når jeg da kjører `yarn` igjen får jeg samme feilmelding. 

Hva kan jeg gjøre for å fikse dette?

**Comment by Skagevang** [comment]
@lexnederbragt du må har riktig node versjon. Vi klarer ikke å oppdatere node på byggeren hver gang det kommer en ny versjon. Så hvis du ser [README til byggeren](byggerehttps://github.com/kodeklubben/codeclub-viewer) så anbefaler den å bestemme dette med NVM. I dag bruker vi node 9.8.0. Burde sikkert oppgradere til 10.16.0 nå siden det er LTS. Og kanskje oppdatere wikien på dette repoet så det er mer forståelig

**Comment by tjesi** [comment]
Vi burde absolutt gi beskjed om hvilken versjon av Node og Yarn som til enhver tid burde brukes. Mange vil automatiske gå for nyeste versjon, og dermed få samme problemer som Lex.

**Comment by Skagevang** [comment]
yarn har ikke noe å si, så der kan man kjøre nyeste hele tiden. Og det står i wikien at man må bruke nvm. https://github.com/kodeklubben/oppgaver/wiki/Bygge-oppgavesidene-lokalt#installere-node

Det samme gjør det i codeclub-viewer repoet. I wikien kan det kanskje utdypes mer om hvor viktig dette er og kanskje en bedre forklaring rundt nvm

**Comment by tjesi** [comment]
Eg skal få oppdatert sidene i løpet av et par dager. Kanskje man i mellomtiden kan linke til denne siden for Node: https://nodejs.org/dist/latest-v8.x/ ? Da får man en versjon som funker, ihvertfall gjorde det det for meg og to andre sommerstudenter.

@lexnederbragt : får du det til å funke om du installerer fra den linken istedenfor?

**Comment by lexnederbragt** [comment]
Tja, det får man om man ikke leser instruksene godt nok - jeg klikket på lenken til https://nodejs.org/en/ og installerte det direkte derfra. Nå har jeg fått nvm på plass og fikk node versjonen v9.8.0. 

Men, første `yarn` kjøring gir nå en rekke feilmeldinger. Jeg velger å lukke denne saken her og nå siden node problemet er fikset. Om noen er villig til å hjelpe til med å fikse resten hadde jeg satt pris på det. Jobber på en MacBook Pro med Mojave 10.14.5.
